### ISSUE TITLE
No file found .....#include "sha256.h"

### ISSUE THREAD

**Issue by jainhemendrah** [mdhiggins/ESP8266-HTTP-IR-Blaster#103]
Dear,
  I downloaded the latest IR Controller code. and followed the steps to download the other libraries.
It seems the local file  "sha256.h" is missing

**Comment by mdhiggins** [comment]
You didn’t install Cryptosuite

**Comment by jainhemendrah** [comment]
Hi ,
  I installed CryptoSuite and then I kept getting error io/avr.h not found.
This was reported to be from sha256.cpp file

**Comment by mdhiggins** [comment]
What version of cryptosuite did you install? Can you link me

**Comment by mdhiggins** [comment]
Also if you’re on Linux you make just be missing some critical libraries

Install these at the operating system level

gcc
gcc-avr
avr-libc
avrprog
avrdude

**Comment by jainhemendrah** [comment]
I installed the latest CrytoSuite library.

Sure, Will install gcc,gcc-avr,etc...thanks Michael

**Comment by jainhemendrah** [comment]
I installed  gcc,gcc-avr,.. files.
Again, opened IR  Controller and tried compiling.

Got following errors:

\Sha\sha256.cpp:2:20: fatal error: avr/io.h: No such file or directory #include <avr/io.h>

**Comment by mdhiggins** [comment]
I would post on cryptosuite GitHub and ask the. I’m not sure

**Comment by jainhemendrah** [comment]
You are right. The issue is with CryptoSuite....
