### ISSUE TITLE
Step Speaker and Input Selection

### ISSUE THREAD

**Issue by gokalpakgul** [mdhiggins/ESP8266-HTTP-IR-Blaster#104]
Dear Michael

Thks a lot for your great application. I am new to ESP but was able to control my devices. Please find below volume up request for Denon. I can volume up and down using Alexa with "increase/decrease volume on Denon" command.

Step Speaker

http://212.156.207.71:667/json?pass=pass&plain=[{'type':'raw','data':[263,789,263,1841,263,789,263,789,263,789,263,1841,263,789,263,789,263,789,263,1841,263,1841,263,1841,263,1841,263,789,263,789,263,43572,263,789,263,1841,263,789,263,789,263,789,263,789,263,1841,263,1841,263,1841,263,789,263,789,263,789,263,789,263,1841,263,1841,263,43572],'kHz':38,'pulse':1}]

I want to use below commands. What should I change on the  request above? 

Alexa, set volume to 100 on Denon
Alexa increase/decrease volume by 20 on Denon

It is written in IR Controller Setup below Step Speaker "Accepts values from -10 to +10 for increments. '&repeat=X' will be appended to the end of the URL unless *vol* is included in the URL for location of volumeStep injection" It is not clear to me. Would you please explain?

And also

Alexa "change the input of Denon to cable" works but not "VCR" or "DTR" instead of cable. In fact if I select 1st to cable then give command "change the input to VCR" Alexa changes input. Do you have a comment? What can be the reason and how can I solve it?

Thks in advance

Regards

Gokalp

**Comment by mdhiggins** [comment]
The input naming is annoying and only certain input names work, its a limitation of Alexa and is filtered before any data is sent to the Alexa skill so its out of my hands. That being said I think cable used to work

For the stepSpeaker command with a RAW command you need to include a flag for repeat frequency (the *vol* tag)

Try this

```
http://212.156.207.71:667/json?pass=pass&plain=[{'type':'raw','data':[263,789,263,1841,263,789,263,789,263,789,263,1841,263,789,263,789,263,789,263,1841,263,1841,263,1841,263,1841,263,789,263,789,263,43572,263,789,263,1841,263,789,263,789,263,789,263,789,263,1841,263,1841,263,1841,263,789,263,789,263,789,263,789,263,1841,263,1841,263,43572],'kHz':38,'pulse':1,'repeat':*vol*}]
```
