### ISSUE TITLE
strcasecmp needed, this is a char[] and not a String object

### ISSUE THREAD

**Issue by rselec** [mdhiggins/ESP8266-HTTP-IR-Blaster#106]
https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/blob/5fd479677c0bd6afef97467643598c5b162ab85c/IRController/IRController.ino#L1043

**Comment by mdhiggins** [comment]
Its wrapped in a String() wrapper so this should be functional
Was fixed 21204752dbc6e854456f9b9cd6d31da4128f7b10
