### ISSUE TITLE
NodeMCU rebooting after a few seconds - continuous loop

### ISSUE THREAD

**Issue by kaotix** [mdhiggins/ESP8266-HTTP-IR-Blaster#108]
I have just flashed this to my nodemcu but when it starts running i get the 'ESP8266 IR controller' output in console then the device reboots and just keeps doing this over and over.
I have all default settings at the moment just to test. 
NodeMCU 0.9 (esp-12 module), 80mhz, 115200, 4m (3m spiffs)

` ets Jan  8 2013,rst cause:4, boot mode:(3,2)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
)
`

**Comment by mdhiggins** [comment]
wdt reset means its crashing

Why exactly is usually tough to pinpoint, but here's some things to start with
Make sure you're using the latest version of the code
If you have an extra nodemcu board, try that and see if its reproducible, these do experience hardware failures from time to time
Disconnect everything from the nodemcu (remove from breadboard) and try running it isolated and see if it boots

If those steps don't work let me know

**Comment by kaotix** [comment]
I dont have a spare nodemcu board, I do have ESP-M3 and ESP-01, however. I would presume it may be compatible on those? They have enough flash memory to upload I believe.
I've just tried the nodemcu on it's own, fresh copy of the code and im getting exactly the same message.

**Comment by billcramer07** [comment]
I had the exact same problem using a Adafruit Huzzah. Found out it did not like the wifi reset on GPIO 10. Make line 35 of the code = to 12. Even  though 12 is already defined as IR send pin 3 it should boot into AP mode. Also u must change line 46 to the static IP u want and change line 47 to your gateway address. Even though these can be changed in setup it won't take them.

**Comment by mdhiggins** [comment]
While I agree with the first statement @billcramer07 made, there's no reason overriding the WiFiManager settings should have any impact on booting

**Comment by billcramer07** [comment]
Everytime I would run WiFiManager and enter my gateway and static IP, WiFiManager would override it with the defaults at lines 46 and 47.

**Comment by billcramer07** [comment]
BTW, your video doesn't show the 3 additional lines in Setup to enter the IP, gateway and subnet mask. Took a while to figure it all out. EXCELLENT SKILL FOR ALEXA!!!

**Comment by mdhiggins** [comment]
Those are just placeholder values that are overwritten before they are used line 334-336 from the values stored in the config.json file from WiFiManager
The values are assigned to the staticIPConfig on line 360

You have to have a placeholder value set so that when WiFiManager enters config mode it will see that it’s a static configuration and prompt for the values for the IP/GW/SN

**Comment by mdhiggins** [comment]
Yeah the video was made when everything was dynamic, I added the static stuff after the fact to make port forwarding more stable

**Comment by kaotix** [comment]
I managed to get it working on an ESP-M3. I will have a look.
I can't remember if I tried changing the configpin on these other devices, I'll give that a go later though.

So far I've captured some codes for my TV and they appear to be working with Alexa. It's actually really simple once you get it all up and running which is brilliant.

**Comment by mdhiggins** [comment]
Gonna close this for now, reopen if you're still having issues
