### ISSUE TITLE
received?id=2 wrong

### ISSUE THREAD

**Issue by phili76** [mdhiggins/ESP8266-HTTP-IR-Blaster#109]
https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/blob/c28d3b843eb8aa08c610ece66f66d061c7b9f56b/IRController/IRController.ino#L985-L989

link to the detail pages is maybe a copy paste error

**Comment by mdhiggins** [comment]
Wow good catch, not sure how that made it in there for so long
Fixed
