### ISSUE TITLE
Thank you #2

### ISSUE THREAD

**Issue by neo7530** [mdhiggins/ESP8266-HTTP-IR-Blaster#115]
I wrote a simple shell-script to test new codes, whithout i have to say "Alexa- blah blah.." :)

Feel free to use it. For me, it works. Edit "yourpass" and your Amazon-ID, so it works without reflash your device. (HMAC-SHA256)

###USAGE: ./irblaster.sh A90:SONY:12
code=$1
proto="msg"
pass="yourpass" #PASSWORD TO ACCEPT COMMANDS
ipaddr="12.34.56.78" #IP ADDR BLASTER
port="1234" #PORT BLASTER
epid="1" #DEVICE-ID
mid="aabbccdd-1234-abcd-5678-aabbccddeeff" #MID-DUMMY
etime=`date +%s` #EPOCH TIME FOR AUTH-ALGO
echo "epid= "$epid
echo "mid= "$mid
echo "epoch-time= "$etime
hash=`echo -n $epid$mid$etime | openssl sha256 -hmac "amzn1.account.AXXXXXXXXXXXXXXXXX" | cut -c 10-` #GENERATE HMAC-HASH
echo "building hash from EPID+MID+EPOCH-TIME= "$hash
echo "STRING TO IR-BLASTER: http://$ipaddr:$port/$proto?code=$code&pass=$pass&auth=$hash&mid=$mid&epid=$epid&time=$etime&simple=1" #BLAST STRING TO BLASTER-DEVICE
wget -o - "http://$ipaddr:$port/$proto?code=$code&pass=$pass&auth=$hash&mid=$mid&epid=$epid&time=$etime&simple=1"

**Comment by mdhiggins** [comment]
Appreciate you putting this together
Added it to the wiki
https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/wiki/Shell-Command-Testing
