### ISSUE TITLE
crash loop from trigger

### ISSUE THREAD

**Issue by Fmkjr** [mdhiggins/ESP8266-HTTP-IR-Blaster#13]
On the current code with these includes
#include <IRDaikinESP.h>
#include <IRremoteESP8266.h>
#include <IRremoteInt.h>
#include <ArduinoJson.h>
#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <ESP8266HTTPClient.h>
 I get a crash loop after 4 -10 triggers
 a serial dump with comments are as follows
[Serial Dump from Crash.txt](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/files/731275/Serial.Dump.from.Crash.txt)
A power cycle is the only way to restart the device.

Thanks M

**Comment by mdhiggins** [comment]
Looks like you're including extra things that don't need to be there, not sure why you've added those

**Comment by Fmkjr** [comment]
What should I remove.
M 

    On Wednesday, January 25, 2017 7:49 PM, Michael Higgins <notifications@github.com> wrote:
 

 Looks like you're including extra things that don't need to be there, not sure why you've added those—

**Comment by mdhiggins** [comment]
I would only include the things that are on the blueprint on github, no need for extras
```
#include <IRremoteESP8266.h>
#include <ArduinoJson.h>
#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <ESP8266HTTPClient.h>
```

Did you manually add those other imports for a reason? And were there any other changes you made to the blueprint aside from the wifi settings/ports/passes

**Comment by Fmkjr** [comment]
No changes to the blueprint other than the includes Ill remove and retest' Not exactly sure how they were added.

**Comment by Fmkjr** [comment]
Removed the includes. It is looping on boot now. I think there might be a power issue with the esp based on this part of the serial dump 

   ¦ESP8266 IR Controller

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset

**Comment by mdhiggins** [comment]
I would double check your physical wiring and make sure its all appropriate

I’ve occasionally run into issues with ESP being pushed too far into the breadboard and having intermittent shorts and reboots/boot loops, pulling it out of the breadboard partially has fixed this. Additionally try booting the ESP by itself without any of the connections plugged in (isolated, not in the breadboard) and see if you can flash it. 

I suspect this is a hardware related issue.

**Comment by Fmkjr** [comment]
I pulled the ESP out of the board and re-installed it with 5% of the pins showing and it has been running for a hour. It seems you where right on the money with that
