### ISSUE TITLE
Please revert changes from PR #133

### ISSUE THREAD

**Issue by scop** [mdhiggins/ESP8266-HTTP-IR-Blaster#135]
Please revert the changes from PR #133. As detailed in PR #131, the inbound code really needs to be decoded into a uint64_t (e.g. with `strtoull`) to work properly with longer codes.

A concrete example:

Capturing the power button press from a Panasonic TV remote here yields this URL for blasting in the UI: `.../msg?code=40040100BCBD:PANASONIC:48&address=0x4004`

Now, if the code parameter is parsed as `strtoul`, blasting it ends up sending something else; this is shown in the serial console:
```
FFFFFFFF:panasonic:48
Address: 16388
```

...and the TV doesn't react. However, when it is parsed with `strtoull` as in PR #131, blasting the same URL results in this in serial console:
```
40040100BCBD:panasonic:48
Address: 16388
```

...and the TV reacts to the signal.

**Comment by mdhiggins** [comment]
Reverted, this was my mistake
