### ISSUE TITLE
DNS server configuration missing with lwIP 2.0 -- breaks ESP8266HTTPClient DNS

### ISSUE THREAD

**Issue by zobotek** [mdhiggins/ESP8266-HTTP-IR-Blaster#139]
Not sure why, but using lwIP v2 (MSS=536) breaks the DNS that ESP8266HTTPClient uses.  Not sure if there are other problems with lwIP v2, but my builds run fine (and seem to be stable) if I hard code IP discovery and NTP IP addresses instead of hostnames.  

What this points to is that the IRController setup does not allow configuration of a DNS server as a part of the static IP configuration process.  I'm not sure how lwIP 1.4 successfully (in my LAN at least) determines which DNS server to use, but it does.  And lwIP 2.0 breaks this.  

Should DNS server IP configuration be added?  I don't believe that either assuming that the configured gateway is also a DNS server or getting DNS from DHCP is a good strategy, even if it works most of the time.

**Comment by mdhiggins** [comment]
It’s a known issue and documented in the read me. Its a bug with lwIP and they’re working on fixing it. Just gonna use 1.4 for now until they get it fixed. See the multiple other issues opened related to this for more details. 

The DNS issues are tough cause WiFiManager does not support defining a DNS
