### ISSUE TITLE
Specified Driver Not Working On Mac

### ISSUE THREAD

**Issue by bleightyturner** [mdhiggins/ESP8266-HTTP-IR-Blaster#141]
Wanted to say thanks for writing this program. I'm running macOS 10.12.6 and was having issues getting the driver to show up correctly with the specified one given. After a while I stumbled across this signed driver that worked for me: https://blog.sengotta.net/signed-mac-os-driver-for-winchiphead-ch340-serial-bridge/
One other thing that might be worth mentioning both of the copies I got:
https://www.aliexpress.com/item/1PCS-Wireless-module-CH340-NodeMcu-V3-Lua-WIFI-Internet-of-Things-development-board-based-ESP8266/32665100123.html?spm=a2g0s.9042311.0.0.U5KOIR
https://www.aliexpress.com/item/New-Wireless-module-CH340-NodeMcu-V3-Lua-WIFI-Internet-of-Things-development-board-based-ESP8266-We/32565317233.html?spm=a2g0s.9042311.0.0.U5KOIR

are wider than the version you have which means for a 400 point breadboard it covers all the holes out except the power rows. plan is to try and put some wires underneath that will run out to the remaining spots to get around it but thought I'd mention for those looking.

**Comment by mdhiggins** [comment]
Yours is bigger because you went with the ‘V3’ nodeMCU, which was sort of an unofficial modification to the original nodeMCU design and also significantly larger in size. the V2 nodeMCU was the last official one and retains the smaller footprint
