### ISSUE TITLE
How to change to lwIP 1.4 (Prebuilt)

### ISSUE THREAD

**Issue by katamara** [mdhiggins/ESP8266-HTTP-IR-Blaster#144]
Sorry for the dumb question, but I cannot figure out how to do this step:
As of the ESP8266 Arduino Core 2.4.0 lwIP vesion 2.0 is default. This causes problems and crashing and it is recommended you use lwIP 1.4. Go to Tools > lwIP Variant > lwIP 1.4 (Prebuilt)

I have installed ESP8266 Arduino Core by Installing with Boards Manager 
Boards manager link: http://arduino.esp8266.com/stable/package_esp8266com_index.json

thanks!

**Comment by eukiseioh** [comment]
In arduino app go to tools —> lwIP Variant —-> choose lwIP 1.4

I used lwIP 2.0 version with the same board

**Comment by mdhiggins** [comment]
Yep, you just click those buttons its a setting in the Arduino IDE itself

Don't use lwIP 2.0 until they patch and fix it, I'll post an update whenever that happens

**Comment by katamara** [comment]
In arduino app go to tools —> lwIP Variant —-> choose lwIP 1.4

I do not have this option under tools

**Comment by eukiseioh** [comment]
Tools ——> into your board settings

**Comment by eukiseioh** [comment]
Where you choose, frecuency, port, etc for select board

**Comment by katamara** [comment]
Problem solved: I uninstalled The Arduino IDE and started all over again and this time lwIP Variant showed up under tools.
The issue was that this was not showing as an option the first time.

**Comment by uddhavdave** [comment]
Hi , can anyone tell me how can I change LWIP variant for MakeEspArduino Environment
