### ISSUE TITLE
Sent command

### ISSUE THREAD

**Issue by eukiseioh** [mdhiggins/ESP8266-HTTP-IR-Blaster#145]
Hi, i can scan codes and are displayed on server web when i want send the command via web “http://xxx.xxx.xxx.xxx:port/msg?code=A90:SONY:12&pass=yourpass” say “code sent ok” but don’t work. Any problem with led emitter?
what’s happen? i used 100 ohm to resistor....

**Comment by mdhiggins** [comment]
Probably a hardware problem
Verify using an IR capable camera (most front facing cameras on cell phones) that your LED is lighting up when you issue a command

If not then double check all your wiring (feel free to post a picture of your build and I can take a look)

**Comment by eukiseioh** [comment]
Ok i will send a pic and check wired and led polarity too...

**Comment by eukiseioh** [comment]
![1514575c-4588-4160-9483-25ae759e95ac](https://user-images.githubusercontent.com/32109546/36029071-ecd62920-0da1-11e8-9f2c-f92e881842f6.jpeg)

**Comment by eukiseioh** [comment]
monitor output:
Connection received - MSG
Blasting off
Blocking incoming IR signals
FFD02F:nec:32
Transmission complete
Reenabling receiving
Turning off the LED to save power.

Success! code sent... but don't happens anything

the address opcion field is "0X0" when i learn any code...

**Comment by mdhiggins** [comment]
The address behavior is normal. Only Panasonic codes use that. Wiring looks good so I would check resistors and LED polarity. Use a camera to see if the LED is lighting up as well. If no light then you’ll need to check all your hardware for a bad component

**Comment by eukiseioh** [comment]
Mmmmm  if the LED is not lighting up i will try another resistor (120 ohm for example). I think the led polarity is good. 5,5v —-> resistor 100 ohm —-> + LED (longest pin).

**Comment by thommy6102** [comment]
It seem that you have the V3 Revision of the NodeMCU.
I have had the same problem, and I had roundabout 1V only on Pin 30  Vin. I`ve used Pin 18 VV instead.
I`ve meassured 5V on this pin, and it works for me since several days.

**Comment by eukiseioh** [comment]
@thommy6102 Works Fine!! i changed to Pin VV 
Thank you!
