### ISSUE TITLE
NTP Error

### ISSUE THREAD

**Issue by Fabian234** [mdhiggins/ESP8266-HTTP-IR-Blaster#147]
After i set the WLAN Configuration in the Browser i became the following error in the serial screen. If I enter blastme.local: 80 in the browser the page can not be found. I use lwIP 1.4. Can be the error message because I do not enter a user_ID in the WLAN configuration because I want to control the infrared without Alexa only via the URL?  Have anybody an idea what could go wrong?
![grafik](https://user-images.githubusercontent.com/36413526/36146886-6547aaac-10b6-11e8-8983-845931fae4fc.png)

**Comment by mdhiggins** [comment]
Usually a result of IP settings not being correct (what's your router IP? whats your subnet?)

Also can be a result of lwIP issues, make sure you use version 1.4 not 2.0 though it seems you have that correct

Also, if you are using Windows and don't have Bonjour installed mDNS won't work natively

**Comment by Fabian234** [comment]
Where should I write the IP address of the router? In the program or in the browser in the wireless settings? Should i write the Gateway of the router in or the IP address?

**Comment by mdhiggins** [comment]
In the browser in the wireless settings

Your device IP shoulder be similar to your router except the last segment of the IP

Your default gateway should match your router IP

And your subnet is probably 255.255.255.0

**Comment by eukiseioh** [comment]
@mdhiggins i think you should upgrade tutorial and explain how to change ip settings when we are configuring AP settings first time. By default set 10.xxx.xxx.xxx ip and i think anyone change it because don’t show how to do in the video tutorial.

Thank for all support and listen us

**Comment by mdhiggins** [comment]
Its very basic level networking, like bare minimum so I would hope people attempting an Arduino DIY project would understand that. At some point if I have time I'll remake the video but my schedule is rough so it won't be for a while
The readme always has the most up to date installation instructions
