### ISSUE TITLE
Question : Multiple IR emitters

### ISSUE THREAD

**Issue by inghaj** [mdhiggins/ESP8266-HTTP-IR-Blaster#154]
Second question : Is there a circuit which would allow me to attach 4 or 5 IR emitters to a single NodeMCU? Im fine with them all transmitting the same signal, but I'd like to position a few in different places inside a cabinet, but it's not clear to me how to wire that ?

Thanks again Michael, this is really an awesome project!

Best
James

**Comment by mdhiggins** [comment]
This is just a basic physics question, you can wire the LEDs in series or parallel
Series they will get the same current by less voltage, parallel they will get the same voltage but less current
Either way they will be less bright but depending on your needs you could opt for either

The other option is to use the different output options and fire off different LEDs sequentially with the same or different commands to preserve brightness, see the other issue about multiple commands

**Comment by inghaj** [comment]
Many thanks, very much appreciated :-)
