### ISSUE TITLE
Question : Hex Values

### ISSUE THREAD

**Issue by inghaj** [mdhiggins/ESP8266-HTTP-IR-Blaster#157]
Hi Michael

Sorry- One more question! I've done some googling & I don't seem to be bale to find an answer to this... Is there any way of taking pronto codes (or equivalent) from a site like remote central (i.e. something like what you might find here : http://files.remotecentral.com/library/3-1/denon/receiver/index.html ) and converting that into what seem to be the hex the values you use in your URLs ?

(One major reason for asking is that even if I can record the code from my original remote control, sites like remote central also list "discrete" codes which are not on the original remote - i.e "power on" rather than the "power on / off" you find on the original remote - This allows a lot more flexibility / control when designing Alexa commands...)

Thanks again & sorry for all the questions!

Best
James

**Comment by mdhiggins** [comment]
I use the discrete codes all the time, there's an application called IRScrutinizer that can convert pronto codes to HEX, this is what I use

It looks like the new version of the IR Remote library I'm using in the project added support for pronto codes so hopefully when I have time I can just build in direct support, but for now using IRScrutinizer is the best option

**Comment by inghaj** [comment]
Thanks a lot Michael.
I had been playing with IRScrutinizer... but I couldnt work out what export format to select once I had pasted in the pronto code  ?
Best
James

**Comment by mdhiggins** [comment]
Export to LIRC, that will have all the HEX information you need
