### ISSUE TITLE
Force WiFi Reconfiguration not working

### ISSUE THREAD

**Issue by katamara** [mdhiggins/ESP8266-HTTP-IR-Blaster#162]
The instructions say:
Force WiFi Reconfiguration
Set GPIO10 to ground to force a WiFi configuration reset, this will boot the device into WiFi host mode with an SSID of 'IRBlaster Configuration' and IP of 192.168.4.1

I have tried GPIO10 and also D7, and I wasnt able to get it to reset.  Probably because I am not sure exactly how to set a pin to ground.

I placed a jumper wire from GPIO10 (also tried D7) to one of the GND connections on the NodeMCU ESP8266 and plugged the usb power back into the device.  This didnt reset it.

How do I set one of the pins to ground?  Is this done while the unit is powered up or before it is powered and then you apply power?  How long do I leave it connected to ground?

**Comment by mdhiggins** [comment]
You connect them to a ground volt source like you have described.
The state of the ground pin is printed during the boot sequence on Serial monitor I would start there and see what the reported state is
You need to have it set to ground during boot, after that point (once the boot sequence has completed) you can disconnect, though leaving it set to ground doesn't hurt anything until it resets again.

**Comment by katamara** [comment]
Hmm, OK so that's what I was doing.  I'll go back and try again.  TY

**Comment by katamara** [comment]
Thanks.  I just tried it again with GPIO10 and I was able to reconfigure it.  

Not sure what I did wrong before, but it's working!  thank you

**Comment by mdhiggins** [comment]
Good news everyone
