### ISSUE TITLE
Two isses: External IP access and keeping the device on

### ISSUE THREAD

**Issue by muditgoel92** [mdhiggins/ESP8266-HTTP-IR-Blaster#171]
I am facing two issues:
- While accessing the external IP, it is asking for user ID and password. What ID / password combo is this? I have used my amazon ID / password, Amzn1 ID / password that gave during set-up phase here, host name / password combos, none seem to work

- I can see that the code is compiled and I am able to open the controller from my local IP address. However, I have to everytime press the RST button on the ESP8266, everytime I refresh the page. Also, On the source log, it is able to receive the IR code only once. Not able to recevie it again and it says "turning off LED to save power". After that it dosent receive ay command nor am I am able to refresh the local IP page.

Overall, I think this is the reason the transmitter is also not transmitting it to my TV and Alexa commands are not working.

Your help would be highly appreciated.
Regards,
Mudit

**Comment by muditgoel92** [comment]
Hi, checking if someone can assist me here?

**Comment by mdhiggins** [comment]
Sounds like your ISP is blocking your external request there’s no component of this script that should prompt for a username or password. Post a screenshot

**Comment by muditgoel92** [comment]
![screen shot 2018-05-03 at 10 55 03 am](https://user-images.githubusercontent.com/38600413/39561097-0eb2e03c-4ec1-11e8-9a4d-4d427a437272.png)
![screen shot 2018-05-03 at 10 57 42 am](https://user-images.githubusercontent.com/38600413/39561103-190629ea-4ec1-11e8-9092-ef3be0a75c93.png)
Please find attached. Thanks again for your help.

**Comment by mdhiggins** [comment]
Yeah that login is not from the device
I think your ISP is intercepting the signal on that port
You can try using a different port instead of 80, 80 is often reserved
