### ISSUE TITLE
Error Opening using local IP and generating External IP

### ISSUE THREAD

**Issue by harishb19** [mdhiggins/ESP8266-HTTP-IR-Blaster#174]
These are my config 
i am on esp8266 2.4 and have set lwip to v 1.4 prebuilt 

*WM: WiFi save
*WM: Parameter
*WM: hostname
*WM: test
*WM: Parameter
*WM: passcode
*WM: test123
*WM: Parameter
*WM: port_str
*WM: 667
*WM: Parameter
*WM: user_id
*WM: 
*WM: static ip
*WM: 10.0.1.10
*WM: static gateway
*WM: 10.0.1.1
*WM: static netmask
*WM: 255.255.255.0
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 10.0.1.10
*WM: Connection result: 
*WM: 3
Should save config
WiFi connected! User chose hostname 'test' passcode 'test123' and port '667'
 config...
{"hostname":"test","passcode":"test123","port_str":"667","user_id":"","ip":"10.0.1.10","gw":"10.0.1.1","sn":"255.255.255.0"}
Writing config file
Config written successfully
WiFi configuration complete
Local IP: 10.0.1.10
URL to send commands: http://test.local:667
ArduinoOTA started
MDNS http service added. Hostname is set to test.local:667
HTTP Server started on port 667
Turning off the LED to save power.
Error retrieving external IP
HTTP Code: -1
connection refused
External IP address request took 5003 ms
Ready to send and receive IR signals

this is the what i get when i hit the ip | dns
![image](https://user-images.githubusercontent.com/18478497/39723721-4fa75752-5264-11e8-83ab-ee3097f102f1.png)

**Comment by mdhiggins** [comment]
What’s your routers local IP address?
