### ISSUE TITLE
Device only stays joined to WiFi network for about 10 or 11 seconds

### ISSUE THREAD

**Issue by sdrasmussen** [mdhiggins/ESP8266-HTTP-IR-Blaster#175]
Hi, all.  I am working my way through this project, and have hit a snag.  I can get the nodemcu to join my home WiFi network, and when it does, it answers ping and also web request.  However, it only stays joined to my WiFi network for about 10 or 11 seconds, after which it drops off, and will never join again, until I power cycle the device.  Is anyone else having this issue?

**Comment by mdhiggins** [comment]
What version of lwIP are you using? and did you select the correct board? and what arduino ESP8266 version are you using?

Certain builds of ESP8266 and combinations with lwIP have memory leaks and cause networking problems

Also what hardware are you using?

**Comment by sdrasmussen** [comment]
I am using 1.4 IwIP per your recommendation in the docs.  As for the arduino ESP8266 version, are you talking about my board?  If so, it is a nodemcu 1.0 with cp2102.  Not sure if I am answering your questions properly.  (extreme newb here)

**Comment by mdhiggins** [comment]
Which build of the Arduino ESP8266 Core?
2.4.0 is the recommended one and later version have memory leaks

**Comment by sdrasmussen** [comment]
2.4.1 is what I have installed.

**Comment by mdhiggins** [comment]
Try rolling back to 2.4.0, 2.4.1 definitely is known to have a networking memory leak

Still make sure you use lwIP 1.4 prebuilt

**Comment by sdrasmussen** [comment]
That did it!  You are the best, man.  Thanks a million for your time.  I can't wait to get this thing finished.  I 3D printed a case for it...should turn out looking pretty decent.

**Comment by mdhiggins** [comment]
Feel free to share!
Glad its working
