### ISSUE TITLE
Channel changing

### ISSUE THREAD

**Issue by emogg** [mdhiggins/ESP8266-HTTP-IR-Blaster#176]
Can you give more guidance on channel changing. I can control with channel up/down using
"http://xxx.xxx.xxx.xxx:667/msg?code=400401004C4D:PANASONIC:48&address=0x4004&pass=****", but I fail with channel numbering and naming.

My base url is "http://******.*****:667/json?pass=*****"
Button 1, for example is "data:'01000809',type:'PANASONIC',length:32,address=16388"
A channel named "bbc" and numbered "101"

I've tried "Alexa, change channel to 200 on TV" and get "Sorry TV appears to be malfunctioning"

Similar result with "Alexa, change channel to bbc on device"

Any hints?

**Comment by mdhiggins** [comment]
It uses standard JSON formatting for the channels which you almost nailed except for the `=`

Should be:
`data:'01000809',type:'PANASONIC',length:32,address:16388`

**Comment by emogg** [comment]
Thanks for catching that so quickly, but the results are just the same. i.e "TV malfunctioning". 
I cannot use the name "bbc" either.

From the json object:      "c1": "data:'01000809',type:'PANASONIC',length:32,address:16388",

Question 1: Where is the malfunctioning taking place? I'm using the phrasing from the alexa ChannelController web page.

Question 2: Do I say 101 as "one zero one", or "one hundred and one", possibly "one oh one"?

**Comment by mdhiggins** [comment]
Email me your JSON discovery packet at the bottom of the page

The malfunctioning is probably something with the JSON packet not being correct
The phrasing is flexible and all of those should work

**Comment by emogg** [comment]
I've emailed my json discovery packet to you. Any progress? Is there anything I can pursue?

**Comment by emogg** [comment]
Dunno how it got closed. Finger trouble I suppose

**Comment by mdhiggins** [comment]
Don’t believe I ever got an email. Confirm which email you sent to please and try sending again

**Comment by emogg** [comment]
Seems it went to "notifications@github.com". I just hit reply in thunderbird.
However here is the json contents:

_Censored since you put your IP and pass in there_

**Comment by emogg** [comment]
Well, not really. The IP and pw were dummies. perhaps I should have used more asterisks. Where should I send an email to instead?

**Comment by mdhiggins** [comment]
That's ok, I found your actual database entry so I could see the unedited version

Looks like you left your .local IP address in the base URL instead of your external IP address unlike all the other URLs

**Comment by emogg** [comment]
AH, OK. These old eyes are a bit dim! Thank you for the heads up. It is now possible to change channels. The problem now is to find the most efficient way of saying the channel names for repeatability.

**Comment by mdhiggins** [comment]
Not sure what you mean here
You can either say the channel number of assign a name to the channel, that's pretty much the only options within the channelController

**Comment by emogg** [comment]
Oh, I only meant whether in the IR Controller Device Setup it is better to use "bbc1", "bbc one", or "b.b.c.1" for channel naming etc. I'd like to know what others use. Anyway, for me, this issue is closed. Thanks for all your help.

**Comment by mdhiggins** [comment]
I actually wrote a long algorithm that will try and check against most possibilities that you listed above so that a match can be found regardless but the safest bet is the simplest bbc1 option, that being said I think most of those should be recognized
