### ISSUE TITLE
UNKNOWN code clarification

### ISSUE THREAD

**Issue by chrislawson** [mdhiggins/ESP8266-HTTP-IR-Blaster#177]
Is it expected that you'd get distinct raw code streams with each press of the same remote button?

I've built 3 of these for the 3 Vizio's that I have and they work great. I am now working on my 4th for an Emerson TV (Remote is an NH305UD) whose codes are coming up as UNKNOWN. I'd expected that pressing the same button on the remote would produce the same steam of raw codes but this does not appear to be the case. 

The following 3 code resulted from my pressing the power button on the Emerson remote three different times with a short delay between presses. 

I am trying to determine whether I can use any of these raw streams as a JSON request to emulate the power button press.

If not, any suggestions why the button presses may be received in this manner?

Thanks again for the awesome project!  My wife and kids LOVE it! 

**Press #1**

Data: CF8DC026
Type: UNKNOWN
Length: 34
Address: 0x0
Raw: 8872,4606,438,682,460,634,492,1746,466,654,492,684,414,628,518,682,438,1776,466,708,436,600,466,740,384,684,490,626,466,1746,468,1772,496,1746,492,626,382,876,332,650,492,712,414,596,522,1800,438,630,466,680,438,1882,440,1720,492,1718,470,1746,546,1800,410,626,522,1746,438,1828,412
Timestamp: 23:02:42

**Press #2**

Data: 95C0C1A1
Type: UNKNOWN
Length: 20
Address: 0x0
Raw: 466,374,1266,1092,216,1298,536,432,272,1682,414,5510,322,688,432,4042,320,2006,300,902,152,2114,202,756,410,790,330,764,162,4210,248,4288,274,820,300,984,300,658,434
Timestamp: 23:02:46

**Press #3**

Data: 22AE7A29
Type: UNKNOWN
Length: 3
Address: 0x0
Raw: 222,880,248,5278,246
Timestamp: 23:02:49

**Comment by mdhiggins** [comment]
Raw codes are expected to have some variability but should generally be the same length. The last code is definitely an error and not fully read. Try to optimize conditions when scanning. Close range, block reflective surfaces and do a a series of scans to see what the most consistent length is. The raw code data will likely have some variability but that’s ok.

**Comment by sdrasmussen** [comment]
Let me also chime in.  I just built this as well, and although it is not ideal (and I don't think anything can be done about this at all and it is not Michael's fault), I have found that probably about 10 presses of a button (I do 5x twice) will let you see which code you really OUGHT to use.  If you get the same code 3 or 4 times, that's the one to use, and you shouldn't have any problems at all.  You will get WILDLY varied results sometimes, but there is enough consistency to pick out the best code, and once you have that, you can send that exact code every time.  Thanks again, Michael.

**Comment by mdhiggins** [comment]
Not sure why you guys have such poor scan results I can usually get reliable data first scan. In a series of 10 I’m usually 80-90% consistent. That being said it’s a minor issue and probably stems from cheap IR receiver hardware and suboptimal scanning conditions

**Comment by chrislawson** [comment]
It must have been due to light in the room. I moved the remote as close as I could to the receiver and was able to get it to show NEC codes.
