### ISSUE TITLE
Absolute beginer here

### ISSUE THREAD

**Issue by fah756** [mdhiggins/ESP8266-HTTP-IR-Blaster#178]
It took me hours for the ide to let me upload the file to the esp8266, when it finished uploading I tried configuring it but it didn’t showed up in the wifi list, what could be the issue? I’ve probably done something wrong. 
It says “config gpio pin”

**Comment by mdhiggins** [comment]
The upload process should only take about 30 seconds
I suspect something is wrong with your device
The log should show way more than that too

**Comment by fah756** [comment]
I tried on two esp8266 boards and the issue is the same or did you mean my computer?

**Comment by mdhiggins** [comment]
I meant the boards but if 2 boards are doing it then you need to verify your Arduino IDE settings
What boards are you using specifically and what upload settings are you using?

**Comment by fah756** [comment]
I've used this one https://www.amazon.com/gp/product/B01IK9GEQG/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1 it is the one on the shopping list, I think it would be easier if you tell me the settings I need to use.

**Comment by mdhiggins** [comment]
That’s the board I use and did all the development on so the settings in the readme should be fine
Try a different USB cable, try doing all uploading with the board not plugged into a breadboard

Also send me a screenshot of your IDE window, it should have the upload settings at the bottom

**Comment by mdhiggins** [comment]
Whoops mixed up the people who've been messaging me today, see edits

**Comment by fah756** [comment]
I tried with another usb cable just now and it doesn't work either, this are the screen shots
<img width="1139" alt="log" src="https://user-images.githubusercontent.com/39446251/40285912-78a1d19a-5c6f-11e8-8729-ffd99e7817dc.png">
this is what it shows on the log

<img width="1276" alt="settings" src="https://user-images.githubusercontent.com/39446251/40285913-78e3d5fe-5c6f-11e8-8681-ae13f2edafa3.png">
and these are the settings

**Comment by mdhiggins** [comment]
Alright your settings are all messed up
Change board to NodeMCU 1.0 (ESP-12E Module)
Change Flash Size to 4M (3M SPIFFS)
Change lwIP to 1.4 Prebuilt
Keep 115200
Change CPU frequency to 80 Mhz

Give that a shot

And make sure you’re on 2.4.0 for ESP8266 Arduino Core

**Comment by fah756** [comment]
<img width="291" alt="log" src="https://user-images.githubusercontent.com/39446251/40521556-26004fd8-5f9a-11e8-9a32-4a3819c5db88.png">

this is what i got now.

**Comment by mdhiggins** [comment]
Well that's significant progress! It booted and probably has an accessible webpage
External stuff didn't work but that usually means either you didn't use 2.4.0 and lwIP 1.4 or you configured your networking settings incorrectly

**Comment by fah756** [comment]
How do I check the networking settings? The lwIP 1.4 (pre-built) option does not appear on my pc, I used the compile from source and there is the other option which is “higher bandwidth”, where do I find the 2.4.0 option?
Sorry I really am an absolute beginer

**Comment by mdhiggins** [comment]
In your Arduino IDE go to:
Tools > Board > Board Manager
Type ESP8266
Click on the one option that should appear
Click on select version
Change to 2.4.0 and hit update

After that's done installing go back to lwIP and v1.4 prebuilt should be there now

**Comment by fah756** [comment]
the IR code on my AC does not work, it sends it but it does nothing but I've tried it on my tv and it does, other than that there is nothing more to say than thanks!

**Comment by mdhiggins** [comment]
Very common for AC not to work; often a ton of weird complications with AC units for whatever reason. You can check on https://github.com/markszabo/IRremoteESP8266 and see if someone has posted about your model
