### ISSUE TITLE
send signal from serial

### ISSUE THREAD

**Issue by ErfanDL** [mdhiggins/ESP8266-HTTP-IR-Blaster#179]
Hi. how can I send command from serial console ? for example how to send FFA25D:NEC:32 with serial ?

thanks

**Comment by mdhiggins** [comment]
You can’t, only over HTTP, Serial is just for monitoring

From: ErfanDL
Sent: Sunday, May 20, 2018 1:59 PM
To: mdhiggins/ESP8266-HTTP-IR-Blaster
Cc: Subscribed
Subject: [mdhiggins/ESP8266-HTTP-IR-Blaster] send signal from serial (#179)

Hi. how can I send command from serial console ? for example how to send FFA25D:NEC:32 with serial
thanks
