### ISSUE TITLE
Just a quick question about raw URLs

### ISSUE THREAD

**Issue by sdrasmussen** [mdhiggins/ESP8266-HTTP-IR-Blaster#180]
The raw code URLs are hideously long.  Would there be any problem with using something like Bitly or Tinyurl to shorten the URLs?

**Comment by mdhiggins** [comment]
Who cares? You don’t see the URL after it’s uploaded. You can use redirect services if you disable the security features if you really want but it will makes things less secure and just adds an additional server to jump through increasing latency
