### ISSUE TITLE
Micro hangs when using 2.4.1 of the ESP8266 board package

### ISSUE THREAD

**Issue by ZincBoy** [mdhiggins/ESP8266-HTTP-IR-Blaster#182]
I have been having an issue getting this running.  I found that if I switch the board package back to 2.4.0 from 2.4.1, it seems to run fine.  

With 2.4.1, the micro will respond for 20-40sec and then spit out a "pm open,type 1 0" message on serial.  It will then be unresponsive until reset.  

With 2.4.0, I see the same message, but the micro keeps working.  

I only see the message if I have debug enabled with the wifi level.  The crashing is the same with or without debug though.

**Comment by mdhiggins** [comment]
Its noted in the readme that there are memory leaks and bugs in 2.4.1 and its not ready for prime time usage yet and to stay on 2.4.0 and lwIP 1.4 for now (2.4.1 defaults to lwIP 2.0 which also has DNS issues)
