### ISSUE TITLE
Unable to perform Wi-Fi Reset via GPIO10 to GND

### ISSUE THREAD

**Issue by oldirtyewok** [mdhiggins/ESP8266-HTTP-IR-Blaster#188]
Just wanted to know if there are other ways to perform a wifi reset?  I had accidently cofigured an ip in an incorrect subnet.

I as per instructions bootup with GPIO10 (S3) to gnd rail as well as GND pins in multiple locations of the NODEMCU ESP8266 V3 (not V2).

When the S3 pin is put to gnd and reset button (or plug in USB micro cable), i just get garbage when monitoring the port thru Arduino IDE (1.8.5).  I am wondering if it's because it's a V3 and not the V2.

So long as the GPIO10 is connected to gnd, and pressing the reset button on the NODEMCU, i just continue to get garbage.  Unit does not reset/respond after that.  I need to return GPIO10 back to normal state, then press the reset button again for it to boot up with previously programmed info.

For the longest while I was unable to force Wifi reset mode (192.168.4.1).

However, I worked around it by changing a value in the following line.
 if (!setupWifi(digitalRead(configpin) == LOW))

instead of LOW, I put HIGH in it's place.
Re-flashed the unit, booted up and voila!  In wifi AP mode with default IP of 192.168.4.1
Program wifi info as needed, re-flashed with that value back to the expected LOW value, and reset again.
Wifi config was persisted OK with the correct information.  And am now able to continue on with the configuration of my IR codes for TV, Receiver etc.

**Comment by mdhiggins** [comment]
Yeah you can freely change the blueprint pins to be compatible with your device, no harm there, and you can change from LOW to HIGH or whatever the non-default option is
