### ISSUE TITLE
About port name & cannot get external IP

### ISSUE THREAD

**Issue by chiql** [mdhiggins/ESP8266-HTTP-IR-Blaster#189]
WiFi connected! User chose hostname 'abc' passcode 'pass' and port '667'
 config...
{"hostname":"abc","passcode":"pass","port_str":"667","user_id":"avc","ip":"10.0.1.10","gw":"10.0.1.1","sn":"255.255.255.0"}
Writing config file
Config written successfully
WiFi configuration complete
Local IP: 10.0.1.10
URL to send commands: http://abc.local:667
ArduinoOTA started
MDNS http service added. Hostname is set to abc.local:667
HTTP Server started on port 667
Error retrieving external IP
HTTP Code: -1
connection refused
External IP address request took 8 ms
Warning, user_id appears to be in the wrong format, security check will most likely fail. Should start with amzn1.account.***
Epoch time from timeServer is unexpectedly old, probably failed connection to the time server. Check your network settings
14400
Invalid EPOCH time, security checks may fail if unable to sync with NTP server
Ready to send and receive IR signals

Above is the log file.
I set "port_str":"667" in Linux, is it correct?
Why "Error retrieving external IP"?

**Comment by mdhiggins** [comment]
See my most recent 2 posts here explaining
https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/issues/190
