### ISSUE TITLE
WDT when running on raw ESP8266

### ISSUE THREAD

**Issue by prawlins** [mdhiggins/ESP8266-HTTP-IR-Blaster#190]
I'm just getting going with this project.  I am able to get it to compile and upload, but am getting WDT.

This is what I get with 'configpin' set to 10 and 'pins3' set to 12:

`ESP8266 IR Controller
Config pin GPIO
 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld
`

I then read some issues that mentioned moving the reset pin.  This is what I get with 'configpin' set to 12 and 'pins3' set to 10:

`*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 10.0.1.10
WiFi connected! User chose hostname 'MyHostname' passcode 'MyPassword' and port '80'
WiFi configuration complete
Local IP: 10.0.1.10
URL to send commands: http://MyHostname.local:80
ArduinoOTA started
MDNS http service added. Hostname is set to MyHostname.local:80
HTTP Server started on port 80
Error retrieving external IP
HTTP Code: -1
connection refused
External IP address request took 8 ms

 ets Jan  8 2013,rst cause:4, boot mode:(1,2)

wdt reset
`
It looks to be getting further, but still WDT.

Any ideas where to look?

This is a great project.  I am looking forward to getting it working.  Thanks to all those who have contributed to it.

**Comment by mdhiggins** [comment]
What version of ESP8266 Arduino Core and lwIP are you using?

Sent from Mail for Windows 10

From: prawlins
Sent: Thursday, July 5, 2018 5:25 PM
To: mdhiggins/ESP8266-HTTP-IR-Blaster
Cc: Subscribed
Subject: [mdhiggins/ESP8266-HTTP-IR-Blaster] WDT when running on raw ESP8266(#190)

I'm just getting going with this project. I am able to get it to compile and upload, but am getting WDT.
This is what I get with 'configpin' set to 10 and 'pins3' set to 12:
`ESP8266 IR Controller
Config pin GPIO
ets Jan 8 2013,rst cause:4, boot mode:(3,6)
wdt reset
load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld
`
I then read some issues that mentioned moving the reset pin. This is what I get with 'configpin' set to 12 and 'pins3' set to 10:
`*WM: Connection result:
*WM: 3
*WM: IP Address:
*WM: 10.0.1.10
WiFi connected! User chose hostname 'MyHostname' passcode 'MyPassword' and port '80'
WiFi configuration complete
Local IP: 10.0.1.10
URL to send commands: http://MyHostname.local:80
ArduinoOTA started
MDNS http service added. Hostname is set to MyHostname.local:80
HTTP Server started on port 80
Error retrieving external IP
HTTP Code: -1
connection refused
External IP address request took 8 ms
ets Jan 8 2013,rst cause:4, boot mode:(1,2)
wdt reset
`
It looks to be getting further, but still WDT.
Any ideas where to look?
This is a great project. I am looking forward to getting it working. Thanks to all those who have contributed to it.

**Comment by prawlins** [comment]
I was using 4.2.1.  After reading some of the other issues I have now switched to ESP8266 core 2.4.0 with lwIP prebuilt v1.4.  I also switched from 'Generic ESP8266' to 'NodeMCU 1.0 (ESP-12E Model)'.

This is what I am now getting in the console:

`
ESP8266 IR Controller
Config pin GPIO12 set to: 1
mounted file system
*WM: Adding parameter
*WM: hostname
*WM: Adding parameter
*WM: passcode
*WM: Adding parameter
*WM: port_str
*WM: Adding parameter
*WM: user_id
Using Static IP
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 10.0.1.10
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 0
*WM: SET AP STA
Entered config mode
192.168.4.1
IR Controller Configuration
*WM: 
*WM: Configuring access point... 
*WM: IR Controller Configuration
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
Failed to connect and hit timeout
⸮
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v4ceabea9
~ld
`

There is no response from ping to 192.168.4.1

Do I need to make any changes to my network settings?

**Comment by prawlins** [comment]
I just ordered new devices from Amazon as mentioned in other issues (https://www.amazon.com/gp/product/B01IK9GEQG/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1).  

I figure it is best to start with known good hardware and go from there.

**Comment by mdhiggins** [comment]
Unfortunately that may be the best option. The I haven’t tested on a raw/bare ESP8266 and I know the NodeMCU V2’s work very well without any blueprint changes

Sent from Mail for Windows 10

**Comment by prawlins** [comment]
I got the devices from Amazon today and am seeing identical behavior as before.  

Do I need to put in my network SSID and password?  Any other network settings than need to be adjusted?

I have attached the console output.

[console.txt](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/files/2173096/console.txt)

**Comment by mdhiggins** [comment]
Its just timing out cause you're not connecting
When you boot the device it first boots into access point mode, you have to use your wireless network card and connect to it. The SSID will be **IR Controller Configuration**

After you connect to that device you can access its setup page at 192.168.4.1. Got there and input your actual WiFi information including your SSID and password as well as you IP configuration information

It will save and assuming you entered valid and correct info the device will switch into client move and connect to your wireless network and subsequently the internet. Then it will be accessible from whatever IP address you assigned instead of 192.168.4.1

**Comment by prawlins** [comment]
Okay, I got it to connect to the access point and was able to configure it to access my local network.  However, I am unable to connect to it from my local network.  This is what is displayed in the serial monitor:

`WiFi configuration complete
Local IP: 10.0.1.10
URL to send commands: http://ESP_C2C8CC.local:80
`
I don't believe my router supports mDNS/Bonjour.  I tried to access it through http://10.0.1.10 but it times out.  Is that the right address?

[console2.txt](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/files/2175785/console2.txt)

**Comment by mdhiggins** [comment]
So it looks like it either didn't save the settings you put in, or you didn't put anything in and just went with the default networking settings

Is 10.0.1.10 a valid IP address for your local network? If you don't know how to verify this you can look up the structure of your computers local IP address and base if off that, just changing the last set of numbers to something unique

For example, my computer's address is 10.0.1.4, so I assigned my device to 10.0.1.200
The gateway needs to match the IP address of your router

Its very common for local IP addresses to use 192.168.0.xxx instead of 10.0.1.xxx

If you knew all this and have a stronger understanding of networking basics I apologize

**Comment by mdhiggins** [comment]
In the event that you put in different settings and it just didn't save them make sure you when you upload the blueprint you allocate space for SPIFFS as without that it won't have any filesystem to save to

**Comment by prawlins** [comment]
Got it working.  I set the IP address to 192.168.2.222 and GW to 192.168.2.1.  

Thanks for all the help getting it going!
