### ISSUE TITLE
3D printed case?

### ISSUE THREAD

**Issue by oldirtyewok** [mdhiggins/ESP8266-HTTP-IR-Blaster#192]
Has anyone made a 3d printed case for this project along with Raptordemon's PCB's (big and small versions).?

**Comment by zobotek** [comment]
[IrControllerCase.zip](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/files/2513714/IrControllerCase.zip)

**Comment by chrislawson** [comment]
Here's one for the v1.5 small board. 

[ir_blaster_v1.5_small.zip](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/files/2544196/ir_blaster_v1.5_small.zip)
