### ISSUE TITLE
 There is currently a bug with the latest versions of ESP8266 for Arduino, please use version 2.4.0 along with lwIP v1.4 Prebuilt to resolve this

### ISSUE THREAD

**Issue by Jmilesy** [mdhiggins/ESP8266-HTTP-IR-Blaster#195]
Ok, sorry, I am having a dumb 5 minutes and probably because it is late, but which ESP8266 for Arduino, and sorry, how?

**Comment by mdhiggins** [comment]
Board Manager -> ESP8266

**Comment by Jmilesy** [comment]
I thought it was one of the libraries, rather than the board itself.  Found it when i was more awake this morning :) thank you for your help :)
