### ISSUE TITLE
dies after a few seconds

### ISSUE THREAD

**Issue by dkcsn** [mdhiggins/ESP8266-HTTP-IR-Blaster#196]
What a fantastic project - Thank you for sharing. 
I have a issue - that the ESP8266-HTTP-IR-Blaster dies after a few seconds.
If i have a Ping running to the blaster - the PING and Blaster dies after 3-5 seconds.
I managed several times to recieve IR codes from a remote controller. (I can tell from the Serial Monitor in Arduino)
Also it seems that IR-Blaster dosen't support DHCP adresses - leaving the IP adress field empty dosen't work - fixed IP is still selected. 
I could use some help to have the first issue fixed .   
I dont have any compiling errors.

Multiple libraries were found for "WiFiManager.h"
 Used: /Users/DrSogaard/Documents/Arduino/libraries/WiFiManager
 Not used: /Users/DrSogaard/Documents/Arduino/libraries/WhareHauoraWiFiManager
Using library IRremoteESP8266 at version 2.4.2 in folder: /Users/DrSogaard/Documents/Arduino/libraries/IRremoteESP8266 
Using library ESP8266WiFi at version 1.0 in folder: /Users/DrSogaard/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.1/libraries/ESP8266WiFi 
Using library WiFiManager at version 0.12 in folder: /Users/DrSogaard/Documents/Arduino/libraries/WiFiManager 
Using library ESP8266WebServer at version 1.0 in folder: /Users/DrSogaard/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.1/libraries/ESP8266WebServer 
Using library DNSServer at version 1.1.0 in folder: /Users/DrSogaard/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.1/libraries/DNSServer 
Using library ESP8266mDNS in folder: /Users/DrSogaard/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.1/libraries/ESP8266mDNS (legacy)
Using library ArduinoJson at version 5.11.1 in folder: /Users/DrSogaard/Documents/Arduino/libraries/ArduinoJson 
Using library ESP8266HTTPClient at version 1.1 in folder: /Users/DrSogaard/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.1/libraries/ESP8266HTTPClient 
Using library ArduinoOTA at version 1.0 in folder: /Users/DrSogaard/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.1/libraries/ArduinoOTA Using library Cryptosuite-master in folder: /Users/DrSogaard/Documents/Arduino/libraries/Cryptosuite-master (legacy)
Using library Ticker at version 1.0 in folder: /Users/DrSogaard/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.1/libraries/Ticker 
Using library EasyNTPClient at version 1.1.0 in folder: /Users/DrSogaard/Documents/Arduino/libraries/EasyNTPClient 

Thank you mdhigging and @raptordemon for PCB

**Comment by mdhiggins** [comment]
See #187
