### ISSUE TITLE
Alexa doesn't understand when being told to change the TV channel up/down

### ISSUE THREAD

**Issue by chiql** [mdhiggins/ESP8266-HTTP-IR-Blaster#200]
So exited when I was able  to turn on/off, volume up/down the Sony TV by Alexa. Thank you for sharing this great project. Below are issues I am facing:

* Channel up/down commands cause errors:
Connection received - JSON
Unauthorized access
Connection received - JSON
Unauthorized access
Connection received - JSON
JSON parsing failed

* Fail to mute

* Cannot access local address of board anymore via web browser after successfully opening the designated port on router

**Comment by mdhiggins** [comment]
Unauthorized access
You either have the wrong passcode or you enabled Alexa security
But if you can't access it from its IP then there's probably more going on

Post a full serial output from boot to command attempts

**Comment by chiql** [comment]
I don't have Alexa now.
Here is what I set the Alexa Skills API for channel control:

- Base URL
 `http://***.***.*.***:667/json?pass=pass`

- Channel Up
 `http://***.***.*.***:667/json?plain=[{'data':'90','type':'SONY','length':12}]?pass=pass`

- Channel Down
`http://***.***.**.***:80/json?plain=[{'data':'890','type':'SONY','length':12}]?pass=pass`
(this is the old IP before I open the port 667) (I forgot the update to new IP)

- 1 Button
`http://***.***.*.***:667/json?plain=[{'data':'10','type':'SONY','length':12}]?pass=pass`

After rechecking, I see the mistake may come from the inconsistency between Channel Up and Channel Down setting, e.g. the port, the external IP are different.

Below is Power On skill command which works:
`http://***.***.*.***:667/msg?code=A90:SONY:12&pass=pass`
(so the wrong password reason is eliminated)

**Comment by mdhiggins** [comment]
Well yeah if you randomly used a different port then it definitely won't work

If you don't have Alexa now then why are you using the skill configuration?
If you want dynamic audio in the JSON option you need to use the *vol* flag too
Also make sure you don't have the user_id option set if you're using this without Alexa

**Comment by chiql** [comment]
>Well yeah if you randomly used a different port then it definitely won't work

No. Port 80 was used when I did not know to open the port on router.
Port 667 was used later when I did open it on the router (port 80 cannot be opened in my case).

>If you don't have Alexa now then why are you using the skill configuration?

I had Alexa when I tested the Sony TV. I borrowed it from my friend, I returned it some weeks ago. That's why I cannot get fail log unless I borrow it again.

>If you want dynamic audio in the JSON option you need to use the vol flag too

You means the Step Speaker, right? If yes, when I don't set the vol flag, the step is +-1

>Also make sure you don't have the user_id option set if you're using this without Alexa

I did test with Alexa.

**Comment by mdhiggins** [comment]
You need to specify the *vol* flag like this

`http://***.***.*.***:667/json?plain=[{'data':'90','type':'SONY','length':12,'repeat':*vol*}]?pass=pass`

If you set up user_id then it requires the authentication components that the skill provides, so if you are testing without Alexa now by trying to use the direct URLs you will get the Unauthorized access error message you're getting, or if you set the user_id incorrectly
