### ISSUE TITLE
Trigger output with IR input?

### ISSUE THREAD

**Issue by P11x3l** [mdhiggins/ESP8266-HTTP-IR-Blaster#201]
Can't see anything in the read me or wiki about this, so though I'd ask :)

Can an IR output blast be triggered by an IR input?

For example I want to map an unused button on my tv remote so when I press it the blaster will send power-on IR commands to all of my devices.

Thanks.

**Comment by mdhiggins** [comment]
Not currently a planned feature but could easily be implemented using the ESP8266 IRRemote project that this project utilizes
