### ISSUE TITLE
Sony Bravia TV not adjusting volume 

### ISSUE THREAD

**Issue by LG02** [mdhiggins/ESP8266-HTTP-IR-Blaster#202]
Brilliant work, thank you.

Please assist, I am unable to change volume up/down on a Sony Bravia TV. Using the following code 
http://192.168.0.31:667/msg?code=490:SONY:12
Alexa responds correctly, and the volume icon appears to increase volume, however the same code needs to be repeated for it to work. My guess is the that the repeat Url is not being added to the end of the command. Any suggestions? Ive tried asking Alexa to increase/decrease volume by increments, but no joy.

Thanks for your wonderful project.

**Comment by mdhiggins** [comment]
Looks like you're using a local IP address, you need to use your external IP address
