### ISSUE TITLE
After updating ArduinoJson Library 

### ISSUE THREAD

**Issue by jbabu** [mdhiggins/ESP8266-HTTP-IR-Blaster#203]
Very good Tutorial. But after updating "ArduinoJson" Library version 6 beta. getting this error.

IRController:54: error: 'DynamicJsonBuffer' does not name a type
 DynamicJsonBuffer jsonBuffer;

Update update library

**Comment by jbabu** [comment]
<img width="991" alt="screen shot 2018-08-17 at 10 55 51 pm" src="https://user-images.githubusercontent.com/7262016/44279887-bfa37e80-a270-11e8-911e-bb943fa4b919.png">

**Comment by mdhiggins** [comment]
Beta 6 is not supported
Its a major rewrite that will require lots of updates and they are still changing it
Once it goes final the script will be updated to support version 6 but for now please use the last stable version
