### ISSUE TITLE
Faulty remote, trying to add raw codes

### ISSUE THREAD

**Issue by Jmilesy** [mdhiggins/ESP8266-HTTP-IR-Blaster#204]
HI All,

I was wondering if anyone had any success finding raw codes on the web and adding them to the Amazon skill?

3 year old managed to destroy a remote and as I was using this anyway, I thought it would be an idea to add as many functions as possible.

I have found raw codes, on the web: http://www.remotecentral.com/cgi-bin/mboard/rc-discrete/thread.cgi?5780 but they seem to be the wrong format, would anyone know if there is a way to convert them?

Many thanks

**Comment by mdhiggins** [comment]
You can just a program called IRScrutinizer to convert those codes to a HEX format by exporting them
