### ISSUE TITLE
DynamicJsonBuffer

### ISSUE THREAD

**Issue by RenderPrism** [mdhiggins/ESP8266-HTTP-IR-Blaster#205]
It looks like [ArduinoJson was changed](https://arduinojson.org/v5/faq/error-jsonbuffer-was-not-declared-in-this-scope/?utm_source=github&utm_medium=issues), and now your blueprint doesn't compile if the latest version of ArduinoJson is installed.

**Comment by mdhiggins** [comment]
#203

**Comment by RenderPrism** [comment]
Apologies, new to Github and only recently worked out how to backtrack through issues.
