### ISSUE TITLE
Increase time of IR signal

### ISSUE THREAD

**Issue by kirananegundi** [mdhiggins/ESP8266-HTTP-IR-Blaster#209]
Hi.  Thanks a lot of this.  I followed it to a tee, and it works perfectly!

One Question.  One the devices I use (IR light switch) needs me to press the button on the controller for a long time (about 2 second).  I am sending a RAW IR command by using a HTTP POST with a JSON object.

Is there any way I can set the 'long press'?﻿

**Comment by mdhiggins** [comment]
You probably need to set a pulse and pdelay to have the signal keep looping for some length of time. You’ll have to play with those values to see what works though not a good way to capture that data

**Comment by kirananegundi** [comment]
Thanks... Will give it a shot.
