### ISSUE TITLE
Air Conditioner Assistance

### ISSUE THREAD

**Issue by oldirtyewok** [mdhiggins/ESP8266-HTTP-IR-Blaster#210]
Hey Michael,

First want to thank you for setting up this project, and your continued support.

I followed your instructions to a T and have a couple units up and running and controlling a few of my devices.

However, I have a stubborn Danby portable AC unit that's refusing to do a simple turn on/off.

My initial IR code captures in serial monitor stated the capture buffer size was too small and to enlarge it. - Done.

I can confirm that ir out LED 4 is indeed blinking (thru cell phone cam) when executing the commands.

here are my codes from Serial Monitor after the increase to capture buffer size.

I'd appreciate if you can take a peek at the raw below and let me know of any pointers you may have to jump this hurdle.

Kind Regards,
Brent

(ON)
`Signal received:
One line: AA98BF65:UNKNOWN:114
uint16_t  rawData[227] = {3640,1440, 572,1138, 572,1140, 570,286, 572,284, 572,284, 572,1142, 540,316, 522,334, 576,1136, 604,1106, 604,246, 606,1114, 570,286, 568,290, 566,1146, 540,1172, 538,318, 540,1174, 538,1174, 536,344, 512,346, 510,1202, 510,348, 508,350, 508,1204, 508,350, 508,350, 508,348, 508,350, 508,350, 508,350, 508,350, 508,350, 508,350, 508,348, 508,350, 508,350, 508,350, 508,1204, 508,350, 508,348, 508,350, 508,1204, 508,350, 508,348, 508,1204, 508,350, 508,350, 508,1202, 508,1204, 508,350, 508,348, 508,350, 508,348, 508,1204, 508,350, 508,1204, 508,1204, 508,1202, 508,348, 508,350, 508,350, 508,348, 508,350, 508,1202, 508,1204, 508,350, 508,1202, 508,1202, 508,1204, 508,350, 508,348, 508,350, 508,350, 508,350, 508,350, 508,348, 508,350, 508,348, 508,350, 508,348, 508,350, 508,350, 508,350, 508,350, 508,348, 508,350, 508,350, 508,350, 508,350, 508,348, 508,350, 508,348, 508,350, 508,350, 508,350, 508,350, 508,1204, 508,1204, 508,350, 508,1202, 508,348, 508,1204, 508,348, 508,350, 508,348, 510,1202, 508,348, 508,1204, 508,350, 508,1204, 508,354, 508};  // UNKNOWN AA98BF65
`

Subsequent URL command:
http://xxx.xxx.xxx.xxx:778/json?plain=[{'data':[3640,1440,572,1138,572,1140,570,286,572,284,572,284,572,1142,540,316,522,334,576,1136,604,1106,604,246,606,1114,570,286,568,290,566,1146,540,1172,538,318,540,1174,538,1174,536,344,512,346,510,1202,510,348,508,350,508,1204,508,350,508,350,508,348,508,350,508,350,508,350,508,350,508,350,508,350,508,348,508,350,508,350,508,350,508,1204,508,350,508,348,508,350,508,1204,508,350,508,348,508,1204,508,350,508,350,508,1202,508,1204,508,350,508,348,508,350,508,348,508,1204,508,350,508,1204,508,1204,508,1202,508,348,508,350,508,350,508,348,508,350,508,1202,508,1204,508,350,508,1202,508,1202,508,1204,508,350,508,348,508,350,508,350,508,350,508,350,508,348,508,350,508,348,508,350,508,348,508,350,508,350,508,350,508,350,508,348,508,350,508,350,508,350,508,350,508,348,508,350,508,348,508,350,508,350,508,350,508,350,508,1204,508,1204,508,350,508,1202,508,348,508,1204,508,348,508,350,508,348,510,1202,508,348,508,1204,508,350,508,1204,508,354,508],'type':'raw','khz':38,'pulse':2,'repeat':2}]&pass=*******&out=4

(OFF)
`Signal received:
One line: ED739373:UNKNOWN:114
uint16_t  rawData[227] = {3638,1440, 572,1140, 570,1140, 572,284, 572,284, 572,284, 570,1142, 540,316, 522,334, 578,1136, 606,1106, 604,248, 604,1114, 568,288, 568,290, 542,1172, 538,1172, 538,318, 540,1174, 536,1174, 536,346, 512,346, 510,1202, 510,348, 508,350, 508,1204, 508,350, 508,348, 508,350, 508,348, 508,350, 508,350, 508,348, 508,350, 508,348, 508,350, 508,348, 510,348, 508,350, 508,1202, 508,348, 508,350, 508,348, 510,348, 508,350, 508,348, 508,1204, 508,348, 508,350, 508,1202, 508,1202, 508,348, 510,348, 508,348, 510,348, 508,1204, 508,348, 508,1202, 508,1204, 508,1204, 508,350, 508,350, 508,350, 508,350, 508,348, 508,1204, 508,1204, 508,348, 508,1204, 508,1204, 508,1204, 508,348, 508,350, 508,348, 508,350, 508,348, 510,348, 508,350, 508,348, 508,350, 508,348, 508,350, 508,348, 510,348, 508,350, 508,348, 508,350, 508,348, 508,350, 508,350, 508,348, 508,350, 508,348, 508,350, 508,348, 508,350, 508,348, 508,1204, 508,1202, 508,1204, 508,350, 508,1202, 508,348, 508,1204, 508,350, 508,1204, 508,350, 508,348, 508,350, 508,1204, 508,350, 508,1202, 508,352, 508};  // UNKNOWN ED739373
`
Subsequent URL command:
http://xxx.xxx.xxx.xxx:778/json?plain=[{'data':[3638,1440,572,1140,570,1140,572,284,572,284,572,284,570,1142,540,316,522,334,578,1136,606,1106,604,248,604,1114,568,288,568,290,542,1172,538,1172,538,318,540,1174,536,1174,536,346,512,346,510,1202,510,348,508,350,508,1204,508,350,508,348,508,350,508,348,508,350,508,350,508,348,508,350,508,348,508,350,508,348,510,348,508,350,508,1202,508,348,508,350,508,348,510,348,508,350,508,348,508,1204,508,348,508,350,508,1202,508,1202,508,348,510,348,508,348,510,348,508,1204,508,348,508,1202,508,1204,508,1204,508,350,508,350,508,350,508,350,508,348,508,1204,508,1204,508,348,508,1204,508,1204,508,1204,508,348,508,350,508,348,508,350,508,348,510,348,508,350,508,348,508,350,508,348,508,350,508,348,510,348,508,350,508,348,508,350,508,348,508,350,508,350,508,348,508,350,508,348,508,350,508,348,508,350,508,348,508,1204,508,1202,508,1204,508,350,508,1202,508,348,508,1204,508,350,508,1204,508,350,508,348,508,350,508,1204,508,350,508,1202,508,352,508],'type':'raw','khz':38,'pulse':2,'repeat':2}]&pass=*******&out=4

**Comment by mdhiggins** [comment]
Air conditioners are notoriously hard to get working due to limitations in the IR library this project uses. Your best bet is to check over on the IR library github page and see if anyone has gotten that particular AC working

https://github.com/markszabo/IRremoteESP8266
