### ISSUE TITLE
IR not blasting

### ISSUE THREAD

**Issue by jpkramm** [mdhiggins/ESP8266-HTTP-IR-Blaster#212]
Hi, I ran into an issue with IR not blasting.  The serial output was 0:nec:32.  It took me a little time to figure out, but it looks like the IR code is being sent from the IR Controller with the "0x" prefix already appended. 
 The code couldn't be sent because of the extra "0x" appended to the dataStr in line 1350.  Tweaking the code as follows resolved the issue for me.
`uint64_t data = strtoull(("0x" + dataStr).c_str(), 0, 0);`
to:
`uint64_t data = strtoull(dataStr.c_str(), 0, 0);`
Cheers!

**Comment by mdhiggins** [comment]
The shorthand format of CODE:FORMAT:LENGTH assumes HEX so you don't need to include the 0x prefix

**Comment by mdhiggins** [comment]
Also 0:NEC:32 is not a valid command, 0 implies no data to be sent

**Comment by jpkramm** [comment]
Understood.  For some reason, sending code=FE4A56AB:NEC:32 resulted in 0:NEC:32 at the client.  The controller automatically added “0x” and then the client added another “0x”, resulting in 0x0xFE4A56AB, which was interpreted as 0:NEC:32.
