### ISSUE TITLE
Sent code displayed is wrong

### ISSUE THREAD

**Issue by regeg** [mdhiggins/ESP8266-HTTP-IR-Blaster#213]
I'm successfully getting the command from Alexa the blaster, but the code blaster reports sending is:

Sent | Command | Type | Length | Address
18:59:48 | FFFFFFFFFFFFFFFF | NEC | 0 | 0X0

Rather than the code sent.  The "NEC" is correct, but that's the only thing that is.

Any recommendations on where to start digging into things?
Thanks!

**Comment by mdhiggins** [comment]
Post your URL without your IP address so I can see what you’re sending

**Comment by regeg** [comment]
So....  When I sent a code today - it worked.  (Volume commands.  I haven't done a JSON packet yet to turn it on w/ the repeated commands.)  But, I'm seeing random sets of FF's on the web page.

![image](https://user-images.githubusercontent.com/2278278/45784650-968f5880-bc37-11e8-94ed-0304ce3e6e7c.png)

**Comment by mdhiggins** [comment]
That’s probably just some IR interference or noise coming from either another device or event ambient light / sunlight
Nothing to be concerned about

**Comment by regeg** [comment]
Well, it's not behaving deterministicly.  I have the following commands defined:
![image](https://user-images.githubusercontent.com/2278278/45787871-677fe380-bc45-11e8-92f0-95db4e6f925e.png)

It looks like the JSON isn't being processed properly.  (I did the 'ON' first then the 'OFF')

![image](https://user-images.githubusercontent.com/2278278/45787895-84b4b200-bc45-11e8-85e1-8a2f6fb49c75.png)

And here's the serial output:
![image](https://user-images.githubusercontent.com/2278278/45787930-ad3cac00-bc45-11e8-963c-bcba8fb959df.png)

These are successive commands without changing anything.
