### ISSUE TITLE
compiler fails 

### ISSUE THREAD

**Issue by ardenking** [mdhiggins/ESP8266-HTTP-IR-Blaster#216]
I’ve installed the libraries but code failed to compile with the following errors any help would be good 

thanks 

Arden 

Arduino: 1.8.7 (Linux), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

IRController:54:1: error: 'DynamicJsonBuffer' does not name a type
 DynamicJsonBuffer jsonBuffer;
 ^
IRController:55:27: error: 'jsonBuffer' was not declared in this scope
 JsonObject& deviceState = jsonBuffer.createObject();
                           ^
/home/arden/Downloads/blaster/ESP8266-HTTP-IR-Blaster-master/IRController/IRController.ino: In function 'String getUserID(String)':
IRController:248:5: error: 'DynamicJsonBuffer' was not declared in this scope
     DynamicJsonBuffer jsonBuffer;
     ^
IRController:248:23: error: expected ';' before 'jsonBuffer'
     DynamicJsonBuffer jsonBuffer;
                       ^
IRController:249:24: error: 'jsonBuffer' was not declared in this scope
     JsonObject& json = jsonBuffer.parseObject(payload);
                        ^
/home/arden/Downloads/blaster/ESP8266-HTTP-IR-Blaster-master/IRController/IRController.ino: In function 'bool setupWifi(bool)':
IRController:393:9: error: 'DynamicJsonBuffer' was not declared in this scope
         DynamicJsonBuffer jsonBuffer;
         ^
IRController:393:27: error: expected ';' before 'jsonBuffer'
         DynamicJsonBuffer jsonBuffer;
                           ^
IRController:394:28: error: 'jsonBuffer' was not declared in this scope
         JsonObject& json = jsonBuffer.parseObject(buf.get());
                            ^
IRController:395:14: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'
         json.printTo(Serial);
              ^
IRController:396:18: error: 'class ArduinoJson::JsonObject' has no member named 'success'
         if (json.success()) {
                  ^
IRController:464:5: error: 'DynamicJsonBuffer' was not declared in this scope
     DynamicJsonBuffer jsonBuffer;
     ^
IRController:464:23: error: expected ';' before 'jsonBuffer'
     DynamicJsonBuffer jsonBuffer;
                       ^
IRController:465:24: error: 'jsonBuffer' was not declared in this scope
     JsonObject& json = jsonBuffer.createObject();
                        ^
IRController:479:10: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'
     json.printTo(Serial);
          ^
IRController:482:10: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'
     json.printTo(configFile);
          ^
/home/arden/Downloads/blaster/ESP8266-HTTP-IR-Blaster-master/IRController/IRController.ino: In lambda function:
IRController:570:5: error: 'DynamicJsonBuffer' was not declared in this scope
     DynamicJsonBuffer jsonBuffer;
     ^
IRController:570:23: error: expected ';' before 'jsonBuffer'
     DynamicJsonBuffer jsonBuffer;
                       ^
IRController:571:23: error: 'jsonBuffer' was not declared in this scope
     JsonArray& root = jsonBuffer.parseArray(server->arg("plain"));
                       ^
IRController:581:15: error: 'class ArduinoJson::JsonArray' has no member named 'success'
     if (!root.success()) {
               ^
IRController:679:42: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonArray&' from an rvalue of type 'ArduinoJson::Internals::enable_if<true, ArduinoJson::Internals::JsonObjectSubscript<const char*> >::type {aka ArduinoJson::Internals::JsonObjectSubscript<const char*>}'
           JsonArray &raw = root[x]["data"]; // Array of unsigned int values for the raw signal
                                          ^
IRController:684:44: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonArray&' from an rvalue of type 'ArduinoJson::Internals::enable_if<true, ArduinoJson::Internals::JsonObjectSubscript<const char*> >::type {aka ArduinoJson::Internals::JsonObjectSubscript<const char*>}'
           JsonArray &pdata = root[x]["data"]; // Array of values for pronto
                                            ^
/home/arden/Downloads/blaster/ESP8266-HTTP-IR-Blaster-master/IRController/IRController.ino: In function 'void cvrtCode(Code&, decode_results*)':
IRController:1205:33: error: 'RAWTICK' was not declared in this scope
       r += results->rawbuf[i] * RAWTICK;
                                 ^
/home/arden/Downloads/blaster/ESP8266-HTTP-IR-Blaster-master/IRController/IRController.ino: In function 'void dumpRaw(decode_results*)':
IRController:1254:39: error: 'RAWTICK' was not declared in this scope
     uint32_t x = results->rawbuf[i] * RAWTICK;
                                       ^
/home/arden/Downloads/blaster/ESP8266-HTTP-IR-Blaster-master/IRController/IRController.ino: In function 'void dumpCode(decode_results*)':
IRController:1287:39: error: 'RAWTICK' was not declared in this scope
     Serial.print(results->rawbuf[i] * RAWTICK, DEC);
                                       ^
exit status 1
'DynamicJsonBuffer' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ardenking** [comment]
rolled back the Json but sill get this 

Arduino: 1.8.7 (Linux), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Build options changed, rebuilding all
/home/arden/Downloads/blaster/ESP8266-HTTP-IR-Blaster-master/IRController/IRController.ino: In function 'void cvrtCode(Code&, decode_results*)':
IRController:1205:33: error: 'RAWTICK' was not declared in this scope
       r += results->rawbuf[i] * RAWTICK;
                                 ^
/home/arden/Downloads/blaster/ESP8266-HTTP-IR-Blaster-master/IRController/IRController.ino: In function 'void dumpRaw(decode_results*)':
IRController:1254:39: error: 'RAWTICK' was not declared in this scope
     uint32_t x = results->rawbuf[i] * RAWTICK;
                                       ^
/home/arden/Downloads/blaster/ESP8266-HTTP-IR-Blaster-master/IRController/IRController.ino: In function 'void dumpCode(decode_results*)':
IRController:1287:39: error: 'RAWTICK' was not declared in this scope
     Serial.print(results->rawbuf[i] * RAWTICK, DEC);
                                       ^
exit status 1
'RAWTICK' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by mdhiggins** [comment]
Due to new IRRemote update, just pushed fix
