### ISSUE TITLE
German Skill commands

### ISSUE THREAD

**Issue by maskiel** [mdhiggins/ESP8266-HTTP-IR-Blaster#219]
Hello !

Is there a german "vocabulary-book"  for the Skill ? 

I found some thread here about the Channel-Controller and some works for me. 
I wonder if there is a commandlist for the playback controller. 

Best regards from Northern Germany
Martin

**Comment by mdhiggins** [comment]
Only what is posted on the Amazon developer website, and even then they seem to change it from time to time without updating or announcing. Short answer is no. For the smart home skills Amazon pretty much defines everything and the skill just translates their API commands into device commands so I do not directly control phrasing/vocabulary.

Is there a specific issue you're having?

**Comment by maskiel** [comment]
Can you please write a link to that Website ? I haven´t found ist yet. 
I tried several Commands and they seem to be very inconsistant, which is uncomfortable to rememember. 

e.g. 

...schalte Fernseher EIN/AUS  (switch TV on/off)
...schalte Fernseher Programm 5  (switch TV program 5)
...Fernseher Lautstärke stummschalten (TV mute)
...schalte Fernseher lauter (switch TV louder) 
...Ein Kanal vor/zurück auf Fernseher (one Channel up/down on TV)
...wechsel auf Fernseher den Kanal zu ZDF (change on TV the channel to ZDF)

………………..
sometimes TV on beginning, sometimes at the end of the command. It seems to be a bit inconsistant. I am searching for a common Grammar in the possible commands. 

I would like to have vocabulary to use the playback-Controller, which I want to use to start and playback timeshift-recording.

**Comment by mdhiggins** [comment]
https://developer.amazon.com/de/docs/device-apis/alexa-channelcontroller.html

That's the most documentation Alexa has published, its not a lot but that's all there is an they do sometimes make changes without updating. Unfortunately its out of my hands and I don't actually have any control as a skill developer of what the commands actually are
