### ISSUE TITLE
RAW captured code and Sony STR-K750P Receiver Issue

### ISSUE THREAD

**Issue by spikked27** [mdhiggins/ESP8266-HTTP-IR-Blaster#22]
Hi, great project!!  I've successfully implemented your code on my ESP8266 and gotten it working with my TV and Roku through my Google Home.

One problem I am running into is with my Sony receiver, the volume up/down codes are captured as:

"640C:SONY:15
unsigned int  rawData[31] = {2450,600, 1300,550, 1250,600, 600,600, 650,600, 1300,600, 600,650, 600,650, 600,650, 600,600, 650,650, 600,600, 1250,600, 1250,600, 650,600, 650};  // SONY 640C
unsigned int  data = 640C;

ED8B792A:UNKNOWN:32
unsigned int  rawData[28] = {600,1250, 600,650, 600,650, 650,1250, 600,600, 650,600, 600,650, 650,600, 650,650, 650,600, 650,1250, 600,1250, 600,650, 600,650 };  // UNKNOWN ED8B792A

240C:SONY:15
unsigned int  rawData[31] = {2450,600, 700,550, 1250,600, 650,600, 650,600, 1250,600, 650,600, 650,600, 650,600, 650,600, 650,600, 650,600, 1250,600, 1250,600, 650,600, 650};  // SONY 240C
unsigned int  data = 240C;

ED8B792A:UNKNOWN:32
unsigned int  rawData[28] = {550,1250, 600,650, 600,650, 600,1250, 600,650, 600,650, 600,650, 600,650, 600,650, 600,650, 650,1200, 600,1250, 600,650, 650,600 };  // UNKNOWN ED8B792A"

When trying the 240C:SONY:15 and 640C:SONY:15 commands that are captured I get no response from the receiver.  Additionally, trying the raw captured code also has no effect.  Any ideas what could be causing this as well as the extra "UNKNOWN" code after each "SONY" command?  

Also, when inputting raw code the serial output is always slightly different than what is entered:
Input:
9100,4500,650,550,600,600,650,1700,650,550,600,600,600,600,600,600,600,600,600,1700,650,1700,600,600,600,1700,600,1700,600,1700,600,1700,650,1700,600,1700,600,1700,600,1700,600,600,600,1700,600,1700,600,1700,600,600,600,600,600,600,600,600,600,1700,600,600,600,600,600,600,600,1700,600

Serial Output:
Connection received - JSON
Raw transmit
Sending code
Sending code
Sending code
3D9518A3:UNKNOWN:32
unsigned int  rawData[67] = {9150,4600, 650,650, 650,650, 700,1750, 700,600, 600,700, 600,700, 650,650, 600,700, 650,1750, 700,1750, 650,650, 600,1800, 650,1800, 600,1800, 650,1800, 650,1800, 650,1800, 600,1800, 650,1750, 650,700, 650,1800, 650,1800, 650,1750, 650,700, 650,650, 650,700, 650,700, 650,1800, 650,700, 550,700, 650,700, 600,1800, 600};  // UNKNOWN 3D9518A3

Any help on these two issue is greatly appreciated, all in all this code is great so thank you for your hard work!!

**Comment by mdhiggins** [comment]
What pulse and pdelay settings have you tried? Sony codes require pulsing the code at a certain interval - usually 3 times in order to be recognized.

Its discussed in other closed issues as far as the best way to determine your delay and pulse values but it varies from device to device.

**Comment by spikked27** [comment]
Yes, actually found one of the closed issues last night and got the receiver to respond to commands with 2-3 pulses and a 40ms delay.  Again, great project and thanks for the reply!
