### ISSUE TITLE
Echo dot can't connect to 'IR device' 

### ISSUE THREAD

**Issue by jonsel087** [mdhiggins/ESP8266-HTTP-IR-Blaster#220]
I was able to set up my device and configure a simple on/off switch for my tv. Tha alexa app detects it, im able to enable but there are no controls like the other device.
Is this expected? Any hints on what to do to troubleshoot? 
When i ask alexa to turn off the &device it says "can't connect to...'. I free tried running dispute) discover new devices but no difference

**Comment by mdhiggins** [comment]
Did you set up port forwarding and use your external IP address? I know you disabled the static IP address settings in favor of DHCP on your other thread which usually only fixes  things if your static networking settings were incorrectly set and that may mean port forwarding is also not correctly set.

**Comment by jonsel087** [comment]
I did enable it (specified internal/external ip and port), but haven't
tested yet that it's working properly with a different application. I'll
try testing it tonight to see if that's the issue

**Comment by jonsel087** [comment]
was able to solve by correctly setting up port forwarding on my router. FYI, for motorola/surfboard routers, you do not specify your external IP, only `0.0.0.0`
