### ISSUE TITLE
Doesn't Compile

### ISSUE THREAD

**Issue by bspiegel33** [mdhiggins/ESP8266-HTTP-IR-Blaster#221]
Great project.  I realize it's been some time since ver 2 was posted.  I am trying to compile the code and getting errors.  Can you identify which versions of the code you used so I can get this to compile?  Much appreciated.  BTW, I am using the ver2 IRController.ino file.

**Comment by mdhiggins** [comment]
I'm not sure specifically, I would try and upgrade to the latest version since the older ones are not supported

**Comment by skorokithakis** [comment]
I made [a fork to add PlatformIO](https://github.com/skorokithakis/ESP8266-HTTP-IR-Blaster) to the library, but it, indeed, [fails with errors](https://travis-ci.com/skorokithakis/ESP8266-HTTP-IR-Blaster/builds/87495047). If you can help me debug this, I can issue a PR for the PlatformIO integration, which will make building and flashing the program basically just `git clone <repo>; platformio run -t upload`.

**Comment by skorokithakis** [comment]
@bspiegel33 You can use #222, it compiles fine.

**Comment by bspiegel33** [comment]
Thanks!  Got it to compile.  I'm new to github so didn't see these additional pull requests.

**Comment by skorokithakis** [comment]
Oh I just made them a few minutes ago.

**Comment by bspiegel33** [comment]
Well, my luck on timing.  Thanks again for sharing it.
