### ISSUE TITLE
strange hitachi tv remote behaviour

### ISSUE THREAD

**Issue by Jmilesy** [mdhiggins/ESP8266-HTTP-IR-Blaster#227]
When i "read" the code from the Hitachi Tv remote i seem to get different codes from the power button:

12:40:09 | C60BDB3D | UNKNOWN | 4 | 0x0
12:40:09 | 84071B38 | UNKNOWN | 6 | 0x0
12:40:04 | D3C1CEA0 | UNKNOWN | 11 | 0x0
12:40:03 | FBCBF994 | UNKNOWN | 11 | 0x0
12:39:57 | 6D58FCC7 | UNKNOWN | 9 | 0x0
12:41:52 | 84C | RC5 | 12 | 0x1
12:41:51 | 4C | RC5 | 12 | 0x1
12:41:50 | 4C | RC5 | 12 | 0x1
12:41:50 | 84C | RC5 | 12 | 0x1
12:42:19 | 96C7569F | UNKNOWN | 11 | 0x0
12:42:18 | 81C65657 | UNKNOWN | 12 | 0x0
12:42:18 | E99DB8FE | UNKNOWN | 11 | 0x0
12:42:18 | 7361AF8F | UNKNOWN | 5 | 0x0
12:42:18 | 942574A7 | UNKNOWN | 11 | 0x0

these are from just pressing the power button, so unsure which code I should use.  Has anyone successfully set these up?

**Comment by mdhiggins** [comment]
Not sure, looks like either a strange encoding or a very poorly received signal. Do other remotes work? Can you try scanning the remote at close range in a dark environment?

**Comment by Jmilesy** [comment]
Thank you for getting back to me

I have tried it in a totally blacked out room and get:

19:20:13 | 84C | RC5 | 12 | 0x1
19:20:12 | 4C | RC5 | 12 | 0x1
19:20:11 | 84C | RC5 | 12 | 0x1
19:20:10 | 4C | RC5 | 12 | 0x1
19:23:02 | 4C | RC5 | 12 | 0x1
19:23:01 | 84C | RC5 | 12 | 0x1
19:23:01 | 84C | RC5 | 12 | 0x1
19:23:00 | 4C | RC5 | 12 | 0x1
19:22:59 | 84C | RC5 | 12 | 0x1

but if I send either, nothing happens.

**Comment by mdhiggins** [comment]
Yeah those are definitely not validly captured codes. Do other remotes give you better and more consistent results or are they all failing? It might be a weird protocol the remote is using

**Comment by Jmilesy** [comment]
All other remotes have worked fine, its just this one, which annoyingly is my main TV.

its Hitachi, so am surprised it does not use a standard protocol.

**Comment by mdhiggins** [comment]
Hitachi actually uses fairly complex proprietary protocols, I would suggest heading over to https://github.com/markszabo/IRremoteESP8266 since that's where the IRRemote library is developed and see if they can help. I would also suggest trying to update your ESP8266 library as it looks like he's been working on improving hitachi support with updates as recently as 6 days ago

**Comment by mdhiggins** [comment]
Another option would be to check out some of the discrete codes for Hitachi TVs and see if you can send them as pronto codes

http://www.remotecentral.com/cgi-bin/codes/hitachi/tv/

**Comment by Jmilesy** [comment]
Brilliant thank you, i did look at the discrete codes, but was not sure how to use them with the blaster

**Comment by mdhiggins** [comment]
Try this for power

```
http://ip:port/json?plain=[{type:'pronto',data:[0x0000, 0x006B, 0x0000, 0x002A, 0x0000, 0x00AC, 0x0000, 0x0015, 0x0000, 0x0015, 0x0000, 0x0015, 0x0000, 0x0015, 0x0000, 0x0040, 0x0000, 0x0015, 0x0000, 0x0040, 0x0000, 0x0015, 0x0000, 0x0040, 0x0000, 0x0040, 0x0000, 0x0040, 0x0000, 0x0040, 0x0000, 0x0015, 0x0000, 0x0040, 0x0000, 0x0015, 0x0000, 0x0040, 0x0000, 0x0040, 0x0000, 0x0040, 0x0000, 0x0040, 0x0000, 0x0015, 0x0000, 0x0040, 0x0000, 0x0015, 0x0000, 0x0015, 0x0000, 0x0015, 0x0000, 0x0015, 0x0000, 0x0015, 0x0000, 0x0015, 0x0000, 0x0040, 0x0000, 0x0015, 0x0000, 0x0040, 0x0000, 0x0040, 0x0000, 0x0040, 0x0000, 0x05F1, 0x0000, 0x0056, 0x0000, 0x0E4F, 0x0000, 0x0056, 0x0000, 0x0E4F, 0x0000, 0x0056, 0x0000, 0x0E4F, 0x0000, 0x0056, 0x0000, 0x12F7]}]
```
