### ISSUE TITLE
compila with errors

### ISSUE THREAD

**Issue by armacali** [mdhiggins/ESP8266-HTTP-IR-Blaster#229]
Arduino:1.8.5 (Mac OS X), Tarjeta:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp: In member function 'void WiFiManager::setupConfigPortal()':
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:146:71: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on(String(F("/")), std::bind(&WiFiManager::handleRoot, this));
                                                                       ^
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:146:71: note: candidates are:
In file included from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:17:0,
                 from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:147:81: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(unsigned char), WiFiManager* const, bool>::type)'
   server->on(String(F("/wifi")), std::bind(&WiFiManager::handleWifi, this, true));
                                                                                 ^
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:147:81: note: candidates are:
In file included from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:17:0,
                 from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:148:83: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(unsigned char), WiFiManager* const, bool>::type)'
   server->on(String(F("/0wifi")), std::bind(&WiFiManager::handleWifi, this, false));
                                                                                   ^
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:148:83: note: candidates are:
In file included from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:17:0,
                 from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:149:83: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on(String(F("/wifisave")), std::bind(&WiFiManager::handleWifiSave, this));
                                                                                   ^
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:149:83: note: candidates are:
In file included from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:17:0,
                 from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:150:72: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on(String(F("/i")), std::bind(&WiFiManager::handleInfo, this));
                                                                        ^
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:150:72: note: candidates are:
In file included from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:17:0,
                 from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:151:73: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on(String(F("/r")), std::bind(&WiFiManager::handleReset, this));
                                                                         ^
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:151:73: note: candidates are:
In file included from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:17:0,
                 from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:153:77: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on(String(F("/fwlink")), std::bind(&WiFiManager::handleRoot, this));  //Microsoft captive portal. Maybe not needed. Might be handled by notFound handler.
                                                                             ^
/Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:153:77: note: candidates are:
In file included from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:17:0,
                 from /Users/armacali/Documents/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/Users/armacali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
exit status 1
Error compilando para la tarjeta NodeMCU 1.0 (ESP-12E Module).

Este reporte podría tener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by armacali** [comment]
solved, just update the ESP8266 drivers

**Comment by chrislawson** [comment]
For more details on updating drivers see https://github.com/esp8266/Arduino#user-content-installing-with-boards-manager
