### ISSUE TITLE
Why this doesn't have MQTT feature. 

### ISSUE THREAD

**Issue by ceaswaran** [mdhiggins/ESP8266-HTTP-IR-Blaster#235]
Why this doesn't have MQTT feature. If MQTT option there its wonderful piece of firmware in the world.
Please add that MQTT IR receive & send feature support

**Comment by mdhiggins** [comment]
MQTT via Amazon's IoT on the ESP8266 is crippled by the lack of memory on the ESP8266. Not enough to handle TLS 1.2 which is the minimum requirement Amazon enforces for authentication. There's are a couple Websocket workarounds than can sort of get it working but hasn't been reliable in my testing. 

Switching to MQTT would also require a complete rewrite of the server backend and accompanying Amazon skill which I simply do not have time to undertake right now.
