### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by rdmorin** [mdhiggins/ESP8266-HTTP-IR-Blaster#238]
I have a new error message when compiling this code. I have successfully compiled and used this code in the past. 

`variable or field 'sendCodePage' declared void`

**Comment by mdhiggins** [comment]
Check your library versions and make sure you're not using a version you shouldn't be, but I would also try cloning the repo again and see if that error sticks cause that's as strange one I wouldn't expect to see and am unable to reproduce
