### ISSUE TITLE
expected unqualified-id before '.' token

### ISSUE THREAD

**Issue by modemmike** [mdhiggins/ESP8266-HTTP-IR-Blaster#239]
Anyone have any idea why I can't compile?

\ir_blaster_sketch\ir_blaster_sketch.ino: In function 'bool validateHMAC(String, String, String, String)':

ir_blaster_sketch:205:11: error: expected unqualified-id before '.' token

     Sha256.initHmac((uint8_t*)key.c_str(), key.length()); // key, and length of key in bytes

           ^

ir_blaster_sketch:206:11: error: expected unqualified-id before '.' token

     Sha256.print(epid);

           ^

ir_blaster_sketch:207:11: error: expected unqualified-id before '.' token

     Sha256.print(mid);

           ^

ir_blaster_sketch:208:11: error: expected unqualified-id before '.' token

     Sha256.print(timestamp);

           ^

ir_blaster_sketch:209:18: error: expected primary-expression before '.' token

     hash = Sha256.resultHmac();

                  ^

ir_blaster_sketch:210:46: error: 'HASH_LENGTH' was not declared in this scope

     String computedSignature = bin2hex(hash, HASH_LENGTH);

                                              ^

exit status 1
expected unqualified-id before '.' token

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by mdhiggins** [comment]
Wrong Sha256 library installed I'm guessing, see the readme and make sure you install Cryptosuite
