### ISSUE TITLE
Import Discrete Remote codes...

### ISSUE THREAD

**Issue by issacsim** [mdhiggins/ESP8266-HTTP-IR-Blaster#24]
First let me thank you for this great project!
My question is can we somehow covert discrete codes like the one below (found on remote central) to be used with the IR Blaster? Sending them as raw and replace spaces with comas? 

0000 006d 0000 0022 00ac 00ac 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0689

**Comment by mdhiggins** [comment]
I'm not 100% sure. I would actually post this question over on the IRremote git page and see what that dev says since he's the author of the library this script implements

https://github.com/z3t0/Arduino-IRremote

**Comment by issacsim** [comment]
Thanks!
