### ISSUE TITLE
Sending Request Locally with Alexa enabled

### ISSUE THREAD

**Issue by BadPapaBear** [mdhiggins/ESP8266-HTTP-IR-Blaster#240]
More of a question/request than an issue. I have recently setup 3x NodeMCU Amica ESP8266 boards using your guide! They are amazing and I wanted to thank you!

What I would like to do would be to not only be able to control the ESP8266's from Alexa but I would also like to be able to control them locally. I plan on creating a file in Anymote using the HTTP commands to design my own remotes/macros/etc. Then I will put this on my/my wife's phone to make managing our TV's since our kids lose the remotes all the time. I saw that someone was working on a way to be able to create a local web server that could use the Alexa key and send the proper codes. 

I believe I saw you posted something about working on a python script to allow this to function but I wasn't sure if there was any progress. I would love to be able to design the remote on a page like what is shown on the wiki then be able to export the page.

Another question just because I am just trying to cover everything while it's on my mind is there an easy way to import remote codes?

**Comment by mdhiggins** [comment]
Not sure specifically what you mean by import remote codes

As far as adding local, yeah its very possible and someone posted a sample script you just need to replicate the authentication process, someone posted a shell command here that does it, but the same could be easily replicated in pretty much any major programming language that has SHA256 HMAC libraries, which should be most

https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/wiki/Shell-Command-Testing
