### ISSUE TITLE
Handy Sony codes

### ISSUE THREAD

**Issue by jameswood** [mdhiggins/ESP8266-HTTP-IR-Blaster#241]
I found some Sony codes online, which aren't available to be learnt from my remote:

Power ON: `750:SONY:12`
Power OFF: `F50:SONY:12`

The standard "on/off" code of A90 is ok, but it's nice to have individual codes for on and off.

These and many others [are listed here](https://openremote.github.io/archive-dotorg/forums/15532260.html)

(this isn't an issue - sorry - but I wasn't sure where to put it and thought it could save others a lot of the searching I went through!)

edit: maybe there could be some Wiki pages for stuff like this? This project brings me so much joy whenever I hear the relay in my old stereo click on. The FUTURE!!)

**Comment by mdhiggins** [comment]
Thanks for sharing!

These are called discrete codes and many TVs (though not all) support them.

http://www.remotecentral.com/ has a huge library of them for many different manufacturers

They're usually presented as pronto codes which can be used directly or converted into HEX codes use IRScrutinizer and then sent

Very useful
