### ISSUE TITLE
exec: "make": executable file not found in %PATH%

### ISSUE THREAD

**Issue by jsg56** [mdhiggins/ESP8266-HTTP-IR-Blaster#245]
Got this error compiling the latest code for the IRBlaster.

**Comment by jsg56** [comment]
The cause is unknown, but here are the files and versions from the Library that compiled and uploaded into the Nodemcu:

File                         | Version

IRremoteESP8266  | 2.5.4
ESP8266WiFi          | 1.0.0
WiFiManager          | 0.12.0
ESP8266mDNS        | 1.2.0
ArduinoJson            | 5.11.1
ESP8266WebServer | 1.0.0
ESP8266HTTPClient | 1.2.0
ArduinoOTA            | 1.0.0
CryptoSuite             | Not in IDE
Time                        | 1.4.0
Ticker                       | 1.0.0
NTP Client                | 3.1.0
Easy NTP Client        | 1.0.0

Now to see if it runs.....

**Comment by jsg56** [comment]
This is the new error message:

Arduino: 1.8.5 (Windows 7), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, 4M (3M SPIFFS), v1.4 Higher Bandwidth, Disabled, None, Only Sketch, 115200"

C:\Users\Kgorris\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0-beta3\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp: In member function 'bool ESP8266WiFiSTAClass::hostname(const char*)':

C:\Users\Kgorris\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0-beta3\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp:537:52: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]

         intf->hostname = wifi_station_get_hostname();

                                                    ^

C:\Users\Kgorris\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0-beta3\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp:539:33: error: 'netif_dhcp_data' was not declared in this scope

         if (netif_dhcp_data(intf) != nullptr) {

                                 ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

So, where am I going wrong?


I'm using a Node MCU V1.0

IRremoteESP8266 | 2.2.4
ESP8266WiFi | 1.0.0
WiFiManager | 0.12.0
ESP8266mDNS | 1.2.0
ArduinoJson | 5.11.1
ESP8266WebServer | 1.0.0
ESP8266HTTPClient | 1.2.0
ArduinoOTA | 1.0.0
CryptoSuite | Installed
Time | 1.4.0
Ticker | 1.0.0
NTP Client | 3.1.0
Easy NTP Client | 1.1.0

**Comment by mdhiggins** [comment]
Appears to be related to your ESP8266WiFi library, I would verify/reinstall/update that to see if this improves things
