### ISSUE TITLE
unnable to connect to the esp

### ISSUE THREAD

**Issue by saikhurana** [mdhiggins/ESP8266-HTTP-IR-Blaster#25]
the device goes into the wifi configuration mode is successfully able to connect to my home network but when i enter the url provided in the serial monitor, it is not able to connect to the http server. But is says server is running when i enter the ip address.

**Comment by mdhiggins** [comment]
To clarify then the IP address works but the more friendly http://device.local doesn't work?

**Comment by saikhurana** [comment]
yeah. that's exactly what i am trying to say

**Comment by mdhiggins** [comment]
That can sometimes be an issue with your router. It's using bonjour/mdns so make sure those services are compatible and enabled

**Comment by saikhurana** [comment]
can you please help me to find this option. i am not familiar with this networking stuff

**Comment by saikhurana** [comment]
Is there any workaround

**Comment by mdhiggins** [comment]
Using the IP address is a good alternative. 

Otherwise I'd need to know your OS and router information

**Comment by saikhurana** [comment]
i use win10 and i have 2 routers. d-link and a binatone.
d-link DSL-2750U Wireless N 300 ADSL2
Binatone WR1500N

**Comment by saikhurana** [comment]
I am fine using the ip address. Can you explain the procedure

**Comment by saikhurana** [comment]
how to connect to the ir remote via ip adress. when i type the local ip address of the it, it just says "Server is running"

**Comment by mdhiggins** [comment]
See the readme for the URL formatting. It's all spelled out very clearly there

**Comment by saikhurana** [comment]
is there a GUI when you use the local host method? is it accessible using the ip address

**Comment by mdhiggins** [comment]
No there is no GUI accept for the initial wifi setup everything else is handled via URL parameters
