### ISSUE TITLE
Use VU instead of VIN if board has VU

### ISSUE THREAD

**Issue by deftdawg** [mdhiggins/ESP8266-HTTP-IR-Blaster#250]
I have a board with a VU pin on it, this pin provides ~5V while on this board VIN provides only ~1.7V.

Not sure the best way to mention this in the doc without creating confusion.  I spent about an hour wondering why I could emit with 3V and not VIN, then googled and discovered the problem was my variant of ESP8266 has a VU pin.

Hopefully this helps someone...

**Comment by helloray** [comment]
I met the same issue.  I tested the VIN voltage and found it's only 1.7V.
