### ISSUE TITLE
NEC Code Address Not Included In Links

### ISSUE THREAD

**Issue by TectonicTMI** [mdhiggins/ESP8266-HTTP-IR-Blaster#256]
Hello, 

After MANY days of troubleshooting (just getting the correct dependencies to build a working firmware was by far the biggest challenge), I thought I had finally gotten everything to work, but when Alexa sends a command, it's not including the Address part of the NEC code, so the sent IR signal is wrong (sends to address 0x0 instead of 0x4). 

Here's an example capture of a known command. As you can see, it's an NEC protocol and the address is 0x4, but the links generated do not provide this address. I assumed it wasn't needed and appended my pass to the end of the URLs and added them to the IR Controller Setup website. 
![image](https://user-images.githubusercontent.com/19977061/58767850-ec95f900-8545-11e9-9844-a07215ad5439.png)

Here is a screenshot of my sent codes. The 14:30:48 code is the one sent by Alexa, as you can see, the address is set to 0x0, which didn't work. The other 4 were me testing URLs by adding the address information, which worked. 

![image](https://user-images.githubusercontent.com/19977061/58767886-8362b580-8546-11e9-9934-692cb9f0a5ef.png)

The manual solution/fix is to append the &address=0x4 to each of my URLs, but I feel like this could/should be fixed in the firmware itself and have it automatically append this data to the generated URLs. 

This doesn't seem to be documented anywhere outside of an obscure Closed Issue regarding the Channel Controller setup that I happened to find while trying to solve a previous issue. In that post, the address field was added to the URLs (even though the "hint" text on the Channel Controllers setup webpage makes zero mention of it). Is this actually documented somewhere and I missed it?

**Comment by mdhiggins** [comment]
Should be fixed
