### ISSUE TITLE
Web Server Not Responding: Static IP issue

### ISSUE THREAD

**Issue by MrBlueWolves** [mdhiggins/ESP8266-HTTP-IR-Blaster#258]
When I set up the wifi network, the page at 192.168.4.1 asks for a Static IP, subnet mask and gateway. This page has more fields than the one in the youtube tutorial. I have tried leaving those fields blank and assigning a static IP but when I monitor the serial port the static IP always ends up being set to 10.0.1.10 and I can't access the web server. My router uses 192.168.1.XXX. Is there a way to disable the static IP setting or to have it actually use the static IP that I assign it. Preferably I'd just like to disable it. I have tried this with lwIP 1.4 (Higher Bandwith) and 2.0 (Higher Bandwith) and 2.0 (Lower memory). When I use lwIP 2.0 I can still see it receive IR messages over the serial monitor. I am using Arduino IDE 1.8.9 and the sparkfun wifi board. https://www.sparkfun.com/products/retired/15000

![Screen Shot 2019-06-22 at 6 24 44 PM](https://user-images.githubusercontent.com/52114964/59969767-0c07bc80-951b-11e9-96f1-7335ef736214.png)

**Comment by morganchristiansson** [comment]
This was mentioned in https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/issues/252#issuecomment-502023174.

Set these variables to empty variables.

```
char static_ip[16] = "";
char static_gw[16] = "";
char static_sn[16] = "";
```

**Comment by MrBlueWolves** [comment]
That worked after I deleted all the data (not just the sketch) and re-uploaded the sketch. Now I still gotta figure out how to connect to the local IP... that doesn't seem to be working but I think there are other guides on that.

**Comment by morganchristiansson** [comment]
Check out #257 I found lots of help there when trying to solve freezes of my WeMos D1 R2

**Comment by mdhiggins** [comment]
This should be resolved on newer builds, especially if using the development branch of WiFi Manager
