### ISSUE TITLE
Wrong platform version referenced in platform.ini?

### ISSUE THREAD

**Issue by PicoMitchell** [mdhiggins/ESP8266-HTTP-IR-Blaster#279]
The commit comment says "Reference released version of espressif8266 platform (points at SDK v2.4)"

But the committed file references the old 1.8.0 version.

https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/commit/3fb812788994e0cbd648e7b770b5b150e396ffa9

**Comment by mdhiggins** [comment]
Should be fixed

**Comment by PicoMitchell** [comment]
Thanks so much for these quick fixes!
