### ISSUE TITLE
Erreur lors de la récupération de l'IP externe #

### ISSUE THREAD

**Issue by slimlesaurien** [mdhiggins/ESP8266-HTTP-IR-Blaster#281]
Salut, seriez-vous en mesure de nous aider avec ce qui suit?

Erreur lors de la récupération du
code HTTP IP externe : -1
connexion refusée
La demande d'adresse IP externe a pris 5002 ms
Aucune erreur détectée avec la configuration de sécurité L'
époque de timeServer est inattendue, probablement la connexion au serveur de temps a échoué. Vérifiez vos paramètres réseau
14400
Heure EPOCH non valide, les vérifications de sécurité peuvent échouer si vous ne pouvez pas vous synchroniser avec le serveur NTP

**Comment by mdhiggins** [comment]
Don't speak French so using translator software

Make sure your network settings are correct (feel free to post your configuration)
Make sure if you're using the main branch that you're using lwIP v1.4 and ESP8266 Core 2.4.0

You can reference the platformio config to see what versions are recommended
```
[env:nodemcuv2]
platform = espressif8266@~2.4.0
board = nodemcuv2
framework = arduino
build_flags = -D PIO_FRAMEWORK_ARDUINO_LWIP_HIGHER_BANDWIDTH # lwIP v1.4
board_build.ldscript = eagle.flash.4m2m.ld
lib_deps =
  IRremoteESP8266@~2.7.5
  WifiManager@~0.15
  ArduinoJson@~6.13.0
  Time@~1.5
  https://github.com/jjssoftware/Cryptosuite.git
monitor_speed = 115200
```

**Comment by slimlesaurien** [comment]
Hello I work under Arduino IDE 1.6.5
i wanted to know if server name i but love or i leave like that

**Comment by mdhiggins** [comment]
IDE should be fine (though it wouldn't hurt to update it). What matters is your library versions as above
Server name can be whatever you want

**Comment by slimlesaurien** [comment]
and for ports and IP I have trouble.
I start on arduino.

**Comment by slimlesaurien** [comment]
alexa answer me:
sorry the TV device is not responding

**Comment by mdhiggins** [comment]
What trouble are you having with port and IP?
I'm happy to help but you need to give way more information

- Serial logging data from the ESP8266 from boot to request
- Information about your local network settings
- Information about you tehpsyc.pythonanywhere.com settings (feel free to censor your external IP)
- Confirmation that you've set up port forwarding and are using your external IP
- What configuration you're putting into WiFiMananger

**Comment by slimlesaurien** [comment]
already first point:
"check-up.dyndns.org"
I have to replace it or not in const char serverName

**Comment by slimlesaurien** [comment]
can you tell me what i should modify on the program thank you

**Comment by mdhiggins** [comment]
You should not need to modify the code at all. You need to post all the above information in full or I can't help you

- Serial logging data from the ESP8266 from boot to request
- Information about your local network settings
- Information about you tehpsyc.pythonanywhere.com settings (feel free to censor your external IP)
- Confirmation that you've set up port forwarding and are using your external IP
- What configuration you're putting into WiFiMananger

**Comment by slimlesaurien** [comment]
![IMG_20200430_173622__01](https://user-images.githubusercontent.com/63542795/80820945-2220e780-8bd8-11ea-99cb-8e8c8ffb9f2b.jpg)

**Comment by mdhiggins** [comment]
That all looks great. Did you set up port forwarding on your router?

**Comment by slimlesaurien** [comment]
no i tried but it didn't work can you help me with that

**Comment by slimlesaurien** [comment]
I don't have a router
just fiber srf box

**Comment by TheMCMan** [comment]
At my girlfriend's I had to login to her internet provider to setup port
forwarding.

The internet provider had port forwarding as a managed service.  It was
Comcast XFi service.

Then I had to turn off advanced monitoring to allow the port forwarding to
actually work...

**Comment by slimlesaurien** [comment]
can you make an example of port forwarding with IP that would help me
thank you in advance

**Comment by mdhiggins** [comment]
Port forwarding is a basic concept in networking not specific to this device/software

https://stevessmarthomeguide.com/understanding-port-forwarding/

You may be better served just googling a guide in your native language but that one may be a helpful starting point. Usually it is through a router but it may depend on how you connect to the internet

**Comment by mdhiggins** [comment]
Going to close this since it's not a technical issue but just a request for help, feel free to keep discussion going

**Comment by slimlesaurien** [comment]
it's good i succeeded 👍
however need help with channel numbers
i don't use roku TV
I saw that there was define chain and wanted to know how to proceed Thank you in advance

**Comment by mdhiggins** [comment]
That just maps names to specific channel numbers

Like HBO -> 14

You still need to code in the individual number buttons in the channel controller (0 through 9) so it knows how to send the individual numbers

**Comment by slimlesaurien** [comment]
I have to add what and where thank you in advance

**Comment by slimlesaurien** [comment]
![Uploading IMG_20200502_173348.jpg…]()

**Comment by slimlesaurien** [comment]
![1588437189169853531675591478137](https://user-images.githubusercontent.com/63542795/80869927-704eed00-8ca3-11ea-9307-983051f64523.jpg)

**Comment by mdhiggins** [comment]
That looks fine

**Comment by mdhiggins** [comment]
You might need to spell out the number though if Alexa struggles with it

**Comment by slimlesaurien** [comment]
how to specify the number seen Alexa tell me no skills active when I say TF1
or else when I say 1 Alexa tell me she can't find the channel

**Comment by slimlesaurien** [comment]
![Screenshot_20200503-134211__01](https://user-images.githubusercontent.com/63542795/80913434-e0fa1600-8d44-11ea-8fd9-ea57d8ae8378.jpg)

**Comment by mdhiggins** [comment]
Are you using your echo in French?
https://developer.amazon.com/en-US/docs/alexa/device-apis/list-of-interfaces.html

the ChannelController API isn't supported in French

**Comment by slimlesaurien** [comment]
hello everyone I have 2 questions
in 1 I have to put what the local address or not
 in 2 sound the code of the key 1 its such well filled for you (key of my TV
Thanks in advance 😉

**Comment by mdhiggins** [comment]
1 needs to be your external IP address but formatted exactly how the placeholder text is
`http://123.456.123.456/json?pass=yourpass`

Replace `123.456.123.456` with your **external** IP
Replace `yourpass` with your passcode if you set one

**Comment by slimlesaurien** [comment]
😭😭😭😭 yes I use echo in France
is there a solution

**Comment by slimlesaurien** [comment]
the link you sent me I don't understand anything can you help me

**Comment by mdhiggins** [comment]
There is no solution for ChannelController until Alexa adds support for your language

**Comment by slimlesaurien** [comment]
a pity for me that there is no French support
Thank you for your help
excellent project 😉.
