### ISSUE TITLE
Volume Increments Default

### ISSUE THREAD

**Issue by The-Arsonist** [mdhiggins/ESP8266-HTTP-IR-Blaster#284]
When I tell alexa to turn TV volume up, it defaults to sending the code 3 times. Is there a way to change this default to one? Also, if I try to use an increment, say I tell alexa to turn the TV volume up by 3, it does it 4 times. If I say 'up by zero' it does it one time.

Here is my Step Speaker/Volume up code:
http://espIP/msg?code=1FE40BF:NEC:32&pass=hunter1&out=1

**Comment by mdhiggins** [comment]
3 is the default and by default it adds one as this was how my TVs worked (first input only shows the bar without increasing)

That being said I see value in having these be configurable so I added parameters on the tehpsyc.pythonanywhere.com page to set these
