### ISSUE TITLE
ESP8266webserver library not found 

### ISSUE THREAD

**Issue by riskyrun** [mdhiggins/ESP8266-HTTP-IR-Blaster#285]
I cannot seem to find the webserver library to download that you suggested in the readme as well as the video.

**Comment by mdhiggins** [comment]
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer

It's part of the core ESP8266 Arduino library and does not need to be installed separately as long as that library is installed

More information about installation here

https://github.com/esp8266/Arduino
