### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by jacobhweeks** [mdhiggins/ESP8266-HTTP-IR-Blaster#295]
Hey MDHIGGINS,

I don't know what happened to my problem report from before, but I found a possible solution. This is the one about Sparkfun WiFi IR Blaster WRL-15031
In the IR rec demo, I found that I needed to adjust the timeout of UNKNOWN signals. I set it to basically ignore unknown signals (1000ms) and that seems to have solved the problem with receiving. I don't remember having that problem with this board, the first board I tried I did not.

The LED problem persists. This board used GPIO 5.

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/issues/294#issuecomment-674339622

You original issue is here but I'll crosspost this
