### ISSUE TITLE
ArduinoJson v6 library on IR Controller with MQTT

### ISSUE THREAD

**Issue by AlexMun070282** [mdhiggins/ESP8266-HTTP-IR-Blaster#296]
Hi, it seems that the IR contorller with MQTT support has not all the latest updates , for example the new ArduinoJson Library.
Could you please add the MQTT support on the latst version of IR controller.ino ?
Really appreciated.

PS. Alexa is now working well slo for Italian language, I've not testet all the commands ...
Thansk

**Comment by mdhiggins** [comment]
No plans to add MQTT support, wouldn't work with the current design of the skill. I did not create the MQTT branch that's someone else's project you'd need to ask them to update the project
