### ISSUE TITLE
Is the python code available anywhere?

### ISSUE THREAD

**Issue by giuliomoro** [mdhiggins/ESP8266-HTTP-IR-Blaster#297]
Is the Python code that is running on https://tehpsyc.pythonanywhere.com available anywhere? I'd be curious to look at it and if possible contribute some of the missing Alexa Interfaces.

**Comment by mdhiggins** [comment]
The server side code is not available, mostly just because I haven't had time to audit the code and I'm not actively developing the project at this time

**Comment by TheMCMan** [comment]
I recommend using IFTTT if you want to customize your service beyond what is provided in the server side code.

I use IFTTT with this project rather than the python code.

**Comment by giuliomoro** [comment]
thanks @TheMCMan , any code you'd be willing to share? I am not familiar with IFTTT, so any hint would be greatly appreciated.

**Comment by mdhiggins** [comment]
IFTTT doesn't require any code you just share the URLs and link your account

You can accomplish basically everything IFTTT offers using the scene controller though
