### ISSUE TITLE
IP issue

### ISSUE THREAD

**Issue by warrenjb** [mdhiggins/ESP8266-HTTP-IR-Blaster#299]
I unplugged the board to move it to another room.  When I reconnected it, it appears the IP address reset to 10.0.1.10.  Any idea why this happened and can I fix it without reflashing the project?  Thanks

**Comment by mdhiggins** [comment]
Did you allocate any space for SPIFFS? You can reset network settings by setting the config pin to ground; see readme

**Comment by warrenjb** [comment]
Thanks for replying.  I'll reset the wifi and try again.  Also, is SPIFFS allocated via Flash Size?  I have FS:2MB OTA:~1019kb selected.  Is that what you recommend?

**Comment by mdhiggins** [comment]
That should be fine, anything with FS > 0
