### ISSUE TITLE
is not working properly  message

### ISSUE THREAD

**Issue by newbee90** [mdhiggins/ESP8266-HTTP-IR-Blaster#304]
When I say Alexa "switch TV on" that answer is TV is not working properly
![bl1](https://user-images.githubusercontent.com/37951740/103464582-3869df00-4d35-11eb-8439-0f4d468c9ad9.jpg)
![bl2](https://user-images.githubusercontent.com/37951740/103464583-39027580-4d35-11eb-94cf-6ba12cd52066.jpg)

**Comment by mdhiggins** [comment]
You need to use the external IP address and have your port forwarded, the local address does not work as the request comes from Amazon's servers on an external network

**Comment by newbee90** [comment]
Now it says xxxxx does not react
![bl3](https://user-images.githubusercontent.com/37951740/103465012-6bfa3880-4d38-11eb-9132-f2be02100b4e.jpg)
![bl4](https://user-images.githubusercontent.com/37951740/103465015-6c92cf00-4d38-11eb-9cc0-bd6f6aa61329.jpg)
but the external IP is changing every night by reconnecting my router

**Comment by mdhiggins** [comment]
If you have a dynamic external IP address you may want to look into a dynamic DNS service

https://www.noip.com/ has a free tier that I use that works nicely

And you need to expose the local IP address of the IR blaster to port 80

To ensure you've done that correctly, you should be able to see the status page using the external IP address. If you cannot, then Alexa cannot either and you'll need to check your router settings

Once everything is working navigating to `http://46.88.xxx.xxx:80` should show the same page as `http://glotze.local:80`

Some ISPs don't allow port 80 so if everything is configured correctly and its still not working try a different port. 80 is generally reserved for HTTP default and ISPs like to block that

**Comment by mdhiggins** [comment]
You don't need to do anything special with your alexa IP address though (I'm assuming that's what the 192.168.178.24 entry is)

**Comment by mdhiggins** [comment]
You need to specify port `80` for "port extern vergeben" for 192.168.178.33 (your IRblaster)

**Comment by mdhiggins** [comment]
Alright so that looks good so far.
The port forwarding and DNS forwarding is working

The error is because your HMAC / Epoch time isn't working for some reason. This did appear to be working previously however. At the bottom of your status page where it says "EPOCH" and gives the numbers, what does it say now?

**Comment by newbee90** [comment]
3162848ms uptime; EPOCH 1609620338 / 1609620340 ( 2 )
Device secured with SHA256 authentication. Only commands sent and verified with Amazon Alexa and the IR Controller Skill will be processed
Error - last authentication failed because your timestamps are out of sync, see serial output for debugging details. Timediff: 1609620265

**Comment by mdhiggins** [comment]
Oh I see what's happening

You can't call the commands from the URL once you turn on the security feature, there's lots of extra data that gets transmitted from the Alexa skill to verify its a valid request

Try using the skill with your updated DNS url and see if things are working after that

Make sure you rerun "Discover devices" with Alexa after you update the URLs though

**Comment by newbee90** [comment]
I delete my device and made a new search
alexa says it don't react

**Comment by mdhiggins** [comment]
Screenshot what you used and send it over

**Comment by mdhiggins** [comment]
And check the serial output and see if it sees the attempt to connect and perhaps why its rejecting

**Comment by newbee90** [comment]
this ist the serial output
![bl6](https://user-images.githubusercontent.com/37951740/103466532-525fed80-4d46-11eb-8527-3a2024387667.jpg)
what is the other screenshot you want?

**Comment by mdhiggins** [comment]
A screenshot of your device settings on the tehpsyc.pythonanywhere.com page

Also, when you set up your dynamic DNS, did you forward it to your external IP address?

**Comment by newbee90** [comment]
![bl7](https://user-images.githubusercontent.com/37951740/103466675-40327f00-4d47-11eb-9125-fab03a1624a6.jpg)

how can I forwarde my external IP adress? it change every night

**Comment by mdhiggins** [comment]
I was able to guess your ddns address and you forwarded it to your local address WHICH WILL NEVER WORK

The whole point of ddns is that it will update as your external IP address updates. Read the documentation on that site. You can set up most routers to tell ddns when the IP changes or install software on your computer that does the same thing

https://www.noip.com/support/knowledgebase/getting-started-with-no-ip-com/

Read step 5

This is networking 101, a local IP address will not work from outside your network

**Comment by newbee90** [comment]
now I have a new problem, http://glotze.xxxx.org deosn't work anymore
Alexa is ok and sending my command, as long i don't renew my IP
after renew my IP i have to start my blaster hardware new

**Comment by mdhiggins** [comment]
Sounds like to just need to fix your dynamic dns and you're all set then

**Comment by newbee90** [comment]
I don't know what to do anymore
![bl8](https://user-images.githubusercontent.com/37951740/103467710-01ee8d00-4d52-11eb-8b95-15ba1122ddac.jpg)
![bl9](https://user-images.githubusercontent.com/37951740/103467711-02872380-4d52-11eb-974c-e79c7cdc8ec8.jpg)
![bl10](https://user-images.githubusercontent.com/37951740/103467747-69a4d800-4d52-11eb-9ce2-e1cbb1f1f2c8.jpg)

**Comment by mdhiggins** [comment]
Is that IP address different than the external one that your blaster device reports or are they the same?
Does going to that external IP address show the status page?
Did you try a different port? As I said before 80 is sometimes not a good choice depending on your ISP

**Comment by mdhiggins** [comment]
I should be able to see your status page using that IP address and I cannot so the forwarding is not working

**Comment by newbee90** [comment]
now port 222 is active and http://46.88.29.35:222/ is working
as long I don't renew my IP
