### ISSUE TITLE
external IP address and port forwarding

### ISSUE THREAD

**Issue by newbee90** [mdhiggins/ESP8266-HTTP-IR-Blaster#305]
You write, "you need to use the external IP address and have your port forwarded"
my external IP adresse changes every night automatically by my router, so it won't work this way
can you give me a examble line for "Power On" in tehpsyc.pythonanywhere.com
i have port forwarded
![bl3](https://user-images.githubusercontent.com/37951740/103465671-6bfd3700-4d3e-11eb-959b-dc35824dc4d5.jpg)
and please do not close this issue so fast

**Comment by mdhiggins** [comment]
Do not create another issue, I will continue support on the original issue

**Comment by newbee90** [comment]
dns service is installed
![bl5](https://user-images.githubusercontent.com/37951740/103466223-56d6d700-4d43-11eb-86a8-a6c076f38fd8.jpg)


21:10:47.824 -> Turning off the LED to save power.
21:25:36.482 -> Connection received
21:27:03.222 -> Transmit NTP Request
21:27:03.222 -> time.google.com: 216.239.35.12
21:27:03.268 -> Receive NTP Response
21:29:43.137 -> Connection received
21:29:59.720 -> Connection received
21:32:37.001 -> Transmit NTP Request
21:32:37.047 -> time.google.com: 216.239.35.0
21:32:37.047 -> Receive NTP Response
21:33:03.862 -> Connection received
21:34:56.470 -> Connection received
21:35:57.624 -> Connection received - MSG
21:35:57.624 -> Failed security check, signature is too old
21:35:57.624 -> Server: 0
21:35:57.624 -> Local: 1609619754
21:35:57.624 -> MID: 
21:36:43.412 -> Connection received - MSG
21:36:43.412 -> Failed security check, signature is too old
21:36:43.412 -> Server: 0
21:36:43.412 -> Local: 1609619800
21:36:43.412 -> MID:

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/issues/304
Redirect here
