### ISSUE TITLE
Sending ecoclim format is not supported

### ISSUE THREAD

**Issue by hllhll** [mdhiggins/ESP8266-HTTP-IR-Blaster#311]
Sending `ecoclim` protocol/format (mostly for controlling HVACs/ACs/Climate devices) is supported by the IR library, but does not work on the firmware.

**Comment by hllhll** [comment]
Can be resolved by merging PR https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/pull/312

**Comment by mdhiggins** [comment]
Any downsides or memory issues increasing the buffer 10 fold?

**Comment by hllhll** [comment]
Aren't all global variables statically defined? If that's too much I guess It would have produced an error. anyway, I'm experimenting with my setup and haven't encountered anything. This valve is based off IRReciveV3 example, that worked while this didn't.
