### ISSUE TITLE
getting error no ntp response

### ISSUE THREAD

**Issue by jayrawatrj** [mdhiggins/ESP8266-HTTP-IR-Blaster#318]
WiFi configuration complete
  Local IP: 10.0.1.10
  DNS IP: 10.0.1.1
  URL to send commands: http://blaster.local:80
  ArduinoOTA started
  MDNS http service added. Hostname is set to blaster.local:80
  HTTP Server started on port 80
  Starting UDP
  Local port: 8888
  Waiting for sync
  Transmit NTP Request
  Turning off the LED to save power.
  time.google.com: 255.255.255.255
  No NTP Response :-(
  Error retrieving external IP
  HTTP Code: -1
  connection failed
  External IP address request took 10276 ms
  Ready to send and receive IR signals

**Comment by jayrawatrj** [comment]
i am not getting the ip address for "time.google.com" as it is showing 255.255.255.255 every time. but when i am running example code from Time library named as "TimeNtp_ESP8266" that code is working fine.

**Comment by mdhiggins** [comment]
Local IP: 10.0.1.10
DNS IP: 10.0.1.1

Are these values valid and on your network subnet? Can't access the internet if they're not

**Comment by jayrawatrj** [comment]
These values are declared in the code itself.

**Comment by jayrawatrj** [comment]
may be i got the solution

**Comment by mdhiggins** [comment]
They are the default values and should be overwritten by the options specified in WiFi manager

**Comment by jayrawatrj** [comment]
ok. got it. Thanks for response
