### ISSUE TITLE
GPIO transmitter.

### ISSUE THREAD

**Issue by lephuvu1994** [mdhiggins/ESP8266-HTTP-IR-Blaster#321]
Thank you very much. Can you help me GPIO transmitter. I want to send infrared signal from all GPIO transmitter pins. What should i do. Thank you. !

**Comment by mdhiggins** [comment]
Either wire your LEDs in series so they all fire off a single pin or if you need individual control just use a JSON command and set your `out` parameter accordingly, you may need to send the same command multiple times over reach out option if you use this method
