### ISSUE TITLE
Setting devices to type “speaker” causes them to show up as “other”

### ISSUE THREAD

**Issue by DragRedSim** [mdhiggins/ESP8266-HTTP-IR-Blaster#322]
Slight glitch with the web control.
Setting the Device Category to “Speakers” causes the device to show up in the Alexa app as “Other”. This is because in the JSON, this is stored as:
`         "displayCategories": [
            "SPEAKERS”
        ],`
This is not a valid option for the Alexa display categories; it is actually looking for “SPEAKER” (no plural), per https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-discovery.html#display-categories . Manually editing the JSON corrects the icon in Alexa, however it means that the web interface no longer recognises the device as a speaker, and sets the category to “Other”, resetting the value on the next save.

**Comment by mdhiggins** [comment]
Should be fixed now, any devices previously set to SPEAKERS should update automatically on the next device update to SPEAKER as well
