### ISSUE TITLE
'USECPERTICK' was not declared in this scope

### ISSUE THREAD

**Issue by vilioren56** [mdhiggins/ESP8266-HTTP-IR-Blaster#330]
Hello everyone, tell me how to solve the problem, using the latest version of the library 2.8.1
`'USECPERTICK' was not declared in this scope`
maybe it should be replaced with another variable?

**Comment by mdhiggins** [comment]
Fixed in #59 in like 2017, are you using a very old version of the blueprint?

**Comment by vilioren56** [comment]
Arduino 1.6.9 and your latest libraries 2.8.1
Please help, a very acute problem

**Comment by mdhiggins** [comment]
Post the full error cause I don't think so, that variable is not referenced in the code anywhere anymore

**Comment by vilioren56** [comment]
Я использую эту переменную, она у меня есть в коде.
Вместо неё надо другую использовать?

**Comment by vilioren56** [comment]
I use this variable, I have it in my code.
Should I use another one instead?

**Comment by mdhiggins** [comment]
If you update to the latest version of the script on Github its no longer used

https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/commit/d95ddff52ce666e9f3d34d3a7b72f6607b5bd77a

It was replaced with RAWTICK 4 years ago

Just update the script

**Comment by vilioren56** [comment]
Instead of USECPERTICK I write RAWTICK?

**Comment by mdhiggins** [comment]
Sure why not. All zero instances
