### ISSUE TITLE
Define LED pin

### ISSUE THREAD

**Issue by Hasenpups** [mdhiggins/ESP8266-HTTP-IR-Blaster#37]
Hello, 

I use your code on a Wemos D1 mini but my hardware is using D4 as the input of the IR receiver. Unfortunately the BUILTIN_LED is also connected to D4 on the WEMOS. 

Is it possible to define the output LED for signals as a parameter so that I can easily adapt this without looking in the whole code?

Suggestion:
const int ledpin = BUILTIN_LED;
replace all BUILTIN_LED with "ledpin" in the sourcecode

**Comment by mdhiggins** [comment]
Done
