### ISSUE TITLE
Send received signal via UDP

### ISSUE THREAD

**Issue by ToB204** [mdhiggins/ESP8266-HTTP-IR-Blaster#40]
Hello,
It is possible to transmit the received IR signals by udp? If yes how?

Thank you Tobi

**Comment by mdhiggins** [comment]
Can you be more specific? Everything is currently done over HTTP so probably not

**Comment by ToB204** [comment]
I would like to send my remote control signals to my [Loxone Miniserver](https://www.loxone.com/enus/). Then I could start with my remote actions in my Smarthome.
Iftt is unfortunately not supported by Loxone.
P.S. Sorry for my english, i come from Germany

**Comment by mdhiggins** [comment]
https://www.loxone.com/enen/kb/virtual-inputs-outputs/

Looks like it should work fine with the HTTP output commands over HTTP
