### ISSUE TITLE
Wifi Manager running instead of IR Blaster Controls

### ISSUE THREAD

**Issue by jfette** [mdhiggins/ESP8266-HTTP-IR-Blaster#44]
To reproduce:

Kill the power to your ESP8226 devices and your wireless router/access points.

Reconnect power to ESP8226 devices.  Wait a minute or so - reconnect power to wireless router.

Eventually the ESP8226 devices will connect back to the wireless that has been saved in config however instead of showing the IR Blaster server pages, we get sent to Wifi manager settings.  This remains until we power cycle or we set the wifi manager settings again.

**Comment by mdhiggins** [comment]
That's the expected behavior of WiFi manager, if the device boots without any WiFi connection it goes into access point mode, and once in that it cannot act as a client to see if the connection has subsequently become available
No good way to improve this behavior unfortunately
