### ISSUE TITLE
Delay between button presses in a sequence 

### ISSUE THREAD

**Issue by Legend2015** [mdhiggins/ESP8266-HTTP-IR-Blaster#46]
Hello, great work on the update. Its been working great for me. I had a query, in sending a button sequence via JSON, I want to incorporate a delay between the button presses. (I want to switch on the TV and then mute it, and want to wait for the tv to switch on before sending the mute command) Is it possible? Going through the readme, it appeared to me that there is a way of specifying Type as Delay, but i couldn't figure out the syntax. Could you please help with that?

**Comment by mdhiggins** [comment]
You either use the rdelay with no repeats after each button press or add a separate dedicated delay. The behavior will be exactly the same. 

{'type':'delay','rdelay':2000}
