### ISSUE TITLE
Slow HTTP Response

### ISSUE THREAD

**Issue by Maruu23** [mdhiggins/ESP8266-HTTP-IR-Blaster#47]
First of all, great job, it works like a charm!
I found out that if I send any code (e.g. "http://hostname.local:80/msg?code=E0E040BF:SAMSUNG:32") the IR Blaster seems to be busy until the http-Response (the HTML) is delivered to the client (e.g. the Browser). Maybe it will be possible to add a get/JSON parameter not to return the full HTML-Response, only the HTTP-Status. It could look like:

http://hostname.local:80/msg?code=E0E040BF:SAMSUNG:32&simpleresponse=1

If the IR code was sent correct, just return HTTP-Status 200 (no HTML-Body). If not, return HTTP-Status 400 with an error message.

**Comment by mdhiggins** [comment]
Great idea, just pushed an update to include this and updated the readme

Add `&simple=1` to achieve this feature
