### ISSUE TITLE
don't add a delay for the last pulse/repeat

### ISSUE THREAD

**Issue by Hasenpups** [mdhiggins/ESP8266-HTTP-IR-Blaster#48]
It is not necessary to add a delay after sending a single IR signal. 

I would recommend to not perform a delay after the last pulse or repeat. 
This will speed up the response of the gateway. 

`if (p + 1 < pulse) delay(pdelay);`

`if (r + 1 < repeat) delay(rdelay);`

**Comment by mdhiggins** [comment]
Great suggestion, just pushed this commit
