### ISSUE TITLE
PCB for this hardware

### ISSUE THREAD

**Issue by raptordemon** [mdhiggins/ESP8266-HTTP-IR-Blaster#50]
Hi,

thanks for building this, just wanted to let you know that i built a PCB for this code.

its not been tested yet but i will report back when its been tested:
https://easyeda.com/raptordemon/ESP8266_IR_blaster-f8f224faba554bf3bb6ce0e32759fc23

cheers!
Raptor

**Comment by mdhiggins** [comment]
This looks really cool
I don't have much experience with this, is the 1.3 revision using the latest pin assignments now?
I'd definitely like to order a couple of these if you've tried
I thought I had replied to this comment earlier and may be going crazy but don't see that reply now
Let me know how it goes! Is this using the V2 nodeMCU?

**Comment by mdhiggins** [comment]
Never mind it was on the pull request that I commented, sanity restored

But yeah definitely keep me posted and send some pics when you get the PCB ordered, I'd like to check it out

**Comment by raptordemon** [comment]
yea sorry about that, feel free to delete one. 

do these look correct?
int pinr1 = gpio14; // Receiving pin
int pins1 = gpio4; // Transmitting preset 1
int pins2 = gpio5; // Transmitting preset 2
int pins3 = gpio12; // Transmitting preset 3
int pins4 = gpio13; // Transmitting preset 4

its for the 25mm / 1in width node mcu like this one:
https://www.amazon.com/Generic-ESP8266-NodeMcu-Internet-Development/dp/B01N0B48NI/ref=sr_1_6?ie=UTF8&qid=1500467677&sr=8-6&keywords=nodemcu

im not sure if that counts as the v2

**Comment by mdhiggins** [comment]
Yeah that's the V2, there's an unofficial V3 version that's larger that was made by some other company, that's why I asked

And those pinouts look correct yes

**Comment by raptordemon** [comment]
great, i m going to reorder the boards this week and hopefully get it right this time.

**Comment by mdhiggins** [comment]
One other question, it looks like the transmitters are using 3.5mm jacks? Maybe the receivers as well. What’s up with that?

**Comment by Hasenpups** [comment]
Just as an information. 
I use the firmware with this hardware: https://www.openhardware.io/view/385/MySWeMosIRShield-IR-blaster-shield-for-WeMos-D1

**Comment by mdhiggins** [comment]
That's pretty cool looking, but looks like no spot for a receiver?

**Comment by mdhiggins** [comment]
Nevermind, just saw the receiver

**Comment by Hasenpups** [comment]
There is a receive on one side between two LEDs. Someone already printed a housing.

https://forum.fhem.de/index.php/topic,72950.msg659524.html#msg659524

**Comment by raptordemon** [comment]
the design for the 3.5mm jacks was so that it could use IR blasters and receivers similar to these:
https://www.amazon.com/dp/B01N674PE9/ref=asc_df_B01N674PE95084387/?tag=hyprod-20&creative=395033&creativeASIN=B01N674PE9&linkCode=df0&hvadid=194024095585&hvpos=1o2&hvnetw=g&hvrand=16751482727696173409&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9024255&hvtargid=pla-312923447038

i figured that it was worth having the option for.

**Comment by mdhiggins** [comment]
Looks like the GPIO15 reset option was causing people a lot of problems, I had to change to GPIO10

Any chance I could get you to at least update the small blueprint? I'm not familiar with this and afraid I'm gonna screw something up

**Comment by raptordemon** [comment]
sure no problem, does GPIO10 work for you? because i had issues with gpio9 and gpio10 in the past

**Comment by mdhiggins** [comment]
GPIO10 is working well for me on the NodeMCU board, can't speak to the other variants but I changed all my boards over to that without problems

Also, I have a new update hopefully coming soon and am looking for a beta tester that uses the IR Blaster with Alexa (and I guess is in the US cause of Amazon's limitations). Any interest?

**Comment by kokarn** [comment]
Just ordered all the parts, this looks amazing. I'll be using it with IFTTT & Google Assistant, is that any help?

PS: The PCBs looks great as well, will get those as well ^^

**Comment by raptordemon** [comment]
HI pcb's updated, v1.5 is the latest it has gpio10 as the wifi reset. i have not tested this board as i am using the v1.3 and still have boards.

please let me know if it works
Raptor

**Comment by mdhiggins** [comment]
Awesome thanks, I'll order some for testing

Also @raptordemon if you use your devices with Alexa, any interest in beta testing something?

**Comment by raptordemon** [comment]
yw.

yea i can do that.

**Comment by mdhiggins** [comment]
Send me an email with your amazon account email address and I'll add you as a beta tester for a new skill

**Comment by ipjcrane** [comment]
It’s ipjcrane@hotmail.com<mailto:ipjcrane@hotmail.com>

**Comment by mdhiggins** [comment]
Invite sent, and sent you an email explaining the new features

**Comment by mdhiggins** [comment]
@ipjcrane @raptordemon 

Any luck with the beta testing?

If you need more help with setup here is a complete setup tutorial video that I finished making that will be live when Amazon enables the V3 API for all users
https://www.youtube.com/watch?v=JysKXOdrOlM

**Comment by KDean7** [comment]
@raptordemon,
Are the circuit boards available yet?  Just starting this project and ordering parts now.  I have no breadboards and just heard about the samples you sent to mdhiggins.  Sounds like they'd be a much cleaner solution.

**Comment by mdhiggins** [comment]
They are available. Use the v1.5 schematic when ordering. For first time builds though I would recommend using a breadboard for testing/debugging

**Comment by w-brown** [comment]
Just wanted to say nice job!   I have built a prototype board using the ESP8266-12E module and am having fun playing with it.   I may decide to develop a board as well and share it out for those who want to reduce the size a bit as the NodeMCU is a bit bulky compared to the ESP module and a few surface mount components.

Do you have any plans to update the interface for the back end server?   One thing that would make it a bit more 'general user' friendly is if you had options not to have to enter the url for each command.  I feel if the interface simply asked for your ip, port, model of device, password, etc... and then for each command only required the hex codes for your remote it would make setting up various devices much simpler. 

In any case, great job!

**Comment by mdhiggins** [comment]
Probably not
While it would make the interface a little cleaner it locks in less flexibility and it would also potentially break compatibility with all the people who have already defined their devices
In the current iteration you can actually combine controlling different controllers within the same virtual device
That being said it would be nice to reduce some of the redundant data. I'll have to see if I can come up with a clever solution that's backward compatible

**Comment by zobotek** [comment]
@raptordemon 

0.  Nice job on the V1.5 PCBs!  Many thanks for sharing.

1.  I just ordered a batch of 10 large and 10 regular V1.5 boards from EasyEDA (China).  Got them and built them up today.  They were cheap - $26 got me 10 of each, including DHL shipping from China. Delivery was 3 days after ordering.  

@raptordemon & @mdhiggins 
2.  Only one problem:  configpin=GPIO10 crashed my NODEMCU board, even without being plugged in to the IR Blaster board.  Solution for me was to use configpin=16 (aka D0).  **It is NOT a good idea to use GPIO10 on a NODEMCU board because it's a reserved pin on some versions, including the NODEMCU Version 0.9 board which uses it for flash chip write control.**  0.9 NODEMCU crashes with pinmode(10,INPUT_PULLUP).  

@raptordemon
3.  Some suggestions for improvement:  
*  make the pin spacing for the resistors wider to accommodate 1/4W resistors
*  put down pads for a micro config switch in addition to a config jumper.  Putting a reset jumper in place on the smaller boards is inconvenient. 
*  put down pads for config mode on GPIO16 to support V0.9 NODEMCU (in addition to those on GPIO10 for V1.0)

**Comment by mdhiggins** [comment]
I think at some point GPIO16 was the reset pin but was causing boot issues though I can’t remember exactly. It’s been quite frustrating finding a reliable reset pin but 10 hasn’t given me any trouble on the V2 nodeMCU which is the latest official

**Comment by KDean7** [comment]
@raptordemon - This may sound really basic but I can't figure out how to order PCB's.  When I go to PCB Order on https://easyeda.com/order, it isn't clear on how to place an order.   Any suggestions?

**Comment by katamara** [comment]
@KDean7 I was having a hard time too.  But I figured it out.  Here's what you need to do:

-go to: https://easyeda.com/raptordemon/ESP8266_IR_blaster-f8f224faba554bf3bb6ce0e32759fc23
-scroll down to the last board
-under the last board, there is a blue box that says "Open in Editor" 
-click that button and it will take you to a new page
-once it loads, there are tabs at the top for all the different board configurations
-choose the tab with the board you want
-next to the website logo , there is a drop down that lets you save the file
-choose save as (if you do not have an account, you will be prompted to create one)
-now choose Generate Gerber File
-at the bottom of the popup screen (you can order from here if you want) there is another button that says "Generate Gerber"
-now you have the gerber file that you can upload to the website that you want to order from.

Does any have any amazon or aliexpress links (or part#'s) for the wifi_reset button and/or the 3.5mm audio jack?

**Comment by katamara** [comment]
> Does any have any amazon or aliexpress links (or part#'s) for the wifi_reset button and/or the 3.5mm audio jack?
I ended up ordering these jacks: https://www.aliexpress.com/item/20PCS-3-5mm-1-8-Female-Audio-Connector-5-Pin-DIP-Stereo-Headphone-Jack-PJ3024M/32689293903.html  they do fit but I have not been able to confirm that they work yet.  they do fit in the holes.  I will update once I can confirm they do indeed work.
for the reset button, I'm just using headers with a jumper.

>

**Comment by katamara** [comment]
I ordered and received the following boards: 
IRBlaster v1.5 small
IRBlaster v1.5

I have soldered components on to the small board, but it's not transmitting IR.  The IR Receiver works fine.
I am wondering if I have 2n2222 and/or IR transmitter backwards.  Has anyone successfully used either of these boards?
If so, which way do these components fit in the board?  ie does the flat side of the component follow the outline on the board?  
Can you post a picture of the completed board?

**Comment by chrislawson** [comment]
Yes, I have successfully assembled the v1.5 small. I am only using one IR transmitter so it did take a bit to ensure that I put all of the components in the right spot. 

Here's a pic before I soldered everything in.
https://imgur.com/a/6YP83FE

**Comment by Masonl23** [comment]
Hey , I got 1.5 board soldered everything up and The reciever works great but only the LED 1 to work and the others don’t. Btw i don’t have the 3 jacks soldered in, Without them does that mean it won’t finish the circuit and doesn’t power the other 3 LED’s? 
Thanks

**Comment by wdavalil** [comment]
hi guys great work really, I order the boar 1.5 I solder everything in place except for the jacks that part I just confess I didn't understood and I still don't know how to do it im about to upload the code but not sure if everything is really in the place im kind of new in all this trying to learn. if someone have a pic showing how is the final result or similar would be really good. thanks ill be updating my progress.

**Comment by Masonl23** [comment]
this is an update 4 months later , i still don’t think the 3 other leds work but it doesn’t matter because i use the 3 aux ports and use a cheap ir emitter cable. This controls my tv , stereo, And light strip combined with alexa is awesome. wdavalil message me i can send you a picture of the final result.

**Comment by raptordemon** [comment]
sorry for the delay, you should not need to populate the jacks for the extra leds to work. ill see if i can test mine

**Comment by RienduPre** [comment]
> I ordered and received the following boards:
> IRBlaster v1.5 small
> IRBlaster v1.5
> 
> I have soldered components on to the small board, but it's not transmitting IR. The IR Receiver works fine.
> I am wondering if I have 2n2222 and/or IR transmitter backwards. Has anyone successfully used either of these boards?
> If so, which way do these components fit in the board? ie does the flat side of the component follow the outline on the board?
> Can you post a picture of the completed board?

Did you ever got it to work? I have the same issue?

**Comment by TheMCMan** [comment]
Hey there.  Got mine to work correctly.  I have a schematic that shows how to correctly determine proper part orientation.  Will post here later today.

Do you have pic of your esp board to place here?  Not sure what you mean by a 1.5 board big and small..

**Comment by RienduPre** [comment]
![45B319A4-C99C-41B0-A550-0BD5D5F1AD4D](https://user-images.githubusercontent.com/9009949/71782617-79bd9680-2fdc-11ea-833d-11e30adba99c.jpeg)
![F6FB4475-B579-48DE-A4C9-A056AF05A1D7](https://user-images.githubusercontent.com/9009949/71782618-79bd9680-2fdc-11ea-9c6f-dd9b84a9013a.jpeg)

**Comment by TheMCMan** [comment]
Hey there, The PCB you posted a pic of is interesting.  It looks like all of the parts are positioned correctly.  Like the flat side of the LED and Transistor are placed correctly, which means the polarity is correct.  I traced the lines from the parts the best I could and everything appears to be good.

Please also send a pic of the ESP8266 board you plug into the headers on the PCB.  Maybe your ESP8266 has a different pinout than what is needed by the PCB.

Attached is a schematic I developed and used for this project based on the project notes:
![IRBlaster-Project_pcb-01-3](https://user-images.githubusercontent.com/55172348/71785243-30f0e800-2fb2-11ea-9875-99240fc34588.png)
 
Here is the PCB i built using this schematic:
![IMG_20191120_225057](https://user-images.githubusercontent.com/55172348/71785503-1ff5a600-2fb5-11ea-96d3-3157048e153d.jpg)

If you use plug connectors, for like the LED, you would be able to swap out the parts more easily to see if you had a part that was malfunctioning.  I am currently transitioning to these connectors for my builds.
![IMG_20200105_121017](https://user-images.githubusercontent.com/55172348/71785556-d8234e80-2fb5-11ea-85e1-dd5f3c5724ec.jpg)

I then put my PCB into a project box.
![enabler-finished-project](https://user-images.githubusercontent.com/55172348/71785717-add29080-2fb7-11ea-9f71-5d4d16f43667.png)

I'm in the process of setting up this device for my disabled friends that are paraplegics or cannot use a remote.  As I too am disabled,

please send a pic of your ESP8266 board

**Comment by RienduPre** [comment]
Here you go.
The only difference I see is that I use a 180 ohm resistor and you 10 ohm

![18CC9097-7109-4307-B7AA-0EFA9F5D5B38](https://user-images.githubusercontent.com/9009949/71808602-82f74380-306e-11ea-876a-78d0c694e283.jpeg)
![2610D044-DFFA-48C2-8D44-735291A329FC](https://user-images.githubusercontent.com/9009949/71808603-82f74380-306e-11ea-92bf-51421029b58c.jpeg)
![0D6E3F97-9C40-4EF0-992A-A9F0126AA040](https://user-images.githubusercontent.com/9009949/71808604-82f74380-306e-11ea-99ec-de47410ec69b.jpeg)
![DD17B79C-F07A-46E3-831E-967D7A780F9A](https://user-images.githubusercontent.com/9009949/71808605-82f74380-306e-11ea-8452-d4a00ff931d7.jpeg)
![821B7D22-0DE4-49A4-9884-ED1215C632C7](https://user-images.githubusercontent.com/9009949/71808607-82f74380-306e-11ea-9591-878f2cfc5c2e.jpeg)

**Comment by TheMCMan** [comment]
That's the exact same ESP8266 board I use : )

Believe you nailed it with your keen observation there lol.  Going from a 10 ohm to an 180 ohm resistor would have a great impact in my opinion.  This resistor size directly controls the brightness of the Infrared LED.  

In the project video of IR Blaster Tutorial, at 1:32 minutes:seconds, mdhiggins references the resistance at 10 ohm as that would provide 500 mAmp current to the IR LED.

The IR Blaster Tutorial video is located here -- [https://youtu.be/JysKXOdrOlM](https://youtu.be/JysKXOdrOlM)

With a little experiment lol, maybe you can tell if you just have a rather dim IR LED bulb... find out exactly where the actual TV IR Receiver is located around the display screen.  What I normally do lol is put the remote like directly against the TV and move it around while pressing the on/off button.  When you identify that sweet spot that turns off the TV you can then hold your IRBlaster, with the IR LED pointed towards the TV of course, and send your commands away.

With any luck you will see that your device works but it's light might be just a bit dim... then replacing the resistor will fix this.  

I did see many diagrams on Google images showing a higher value resistor like you used.  When building mine I tried to just base it off of the video.  But every hurdle in this project seems to be monumental lol.

Out of the 4 boards I've built, I couldn't get 1 to work..  never figured out why, but I think it had a lot to do with my despicable soldering..

**Comment by RienduPre** [comment]
I can't get it to work. I gave up and look for other methods to operate my fire place

**Comment by benlye** [comment]
Just buy one of these.  Works really nicely with Michael's code.
https://www.aliexpress.com/item/32958748327.html

See #236 for more information.

**Comment by mdhiggins** [comment]
@raptordemon not sure if you're still using this project or not, but was wondering if you'd be interested in making a small update to your PCB. I continue to use the 1.5 small version to this day and its been awesome

I'm looking to tweak the design a little in a coming update, removing 4th IR led and subsequent hardware and replacing it with an input using a optocoupler.

The goal is to allow a 5v input/ground from a USB cable to be connected to the optocoupler and then to use GPIO13 as an input pin. This would allow me to detect the TV state using power from the debug USB port present on most TVs for reliable state monitoring to prevent repeat "on" commands from turning a TV off when discrete codes are absent.

I currently have the external/debug USB 5v port with a 220 ohm resistor and external ground connected to one side of the optocoupler with GPIO13 connected on the other side.

The mqttdev branch is updated to include the code

I tried modifying your PCB design myself but realized I have no idea what I'm doing.

You would be able to eliminate one of  the 2N222 transistors and one resistor and repurpose the other resistor for the optocoupler

Here is a quick photo of my test setup

![image](https://user-images.githubusercontent.com/3608298/130816687-e86add58-b62b-432a-8f1f-97668deafd7d.png)

Thanks

**Comment by raptordemon** [comment]
Hi yes I can do that, can you draw out the schematic and let me know the Part numbers

Thanks
Raptor

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdhiggins** [comment]
The part is PC817 optocoupler

I took a crack at it myself if you want to just look it over, its not letting me share the easyEDA project for some reason but I exported it as a DXF 

I'll try and draw out the schematic shortly but that should give you an idea too

[IRBlaster v1.6 small_2021-08-25.zip](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/files/7050039/IRBlaster.v1.6.small_2021-08-25.zip)

**Comment by raptordemon** [comment]
Thanks, had drawn on the back of an envelope is fine :)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdhiggins** [comment]
![image](https://user-images.githubusercontent.com/3608298/130870997-c2fe08c7-ca8e-4276-b16e-020cbc63ce3b.png)

How's that?

The components related to the 4th output LED can be removed
Q4 and R8

R7 repurposed

![image](https://user-images.githubusercontent.com/3608298/130871174-1c8b12b9-4d0b-4f68-ad67-7b8eeb16ffb6.png)

That's what I came up with but I don't know enough to know if that'll work

**Comment by mdhiggins** [comment]
Finally let me share
https://oshwlab.com/mdhiggins23/ESP8266_IR_blaster_copy-73a49d4e049f40d986477c90a3d21e56, 1.6 is the only one I made changes to

**Comment by raptordemon** [comment]
Looks good but i went ahead and remade 1.6 as its own project and redid the board.

https://oshwlab.com/raptordemon/ESP8266_IR_blaster-f8f224faba554bf3bb6ce0e32759fc23_copy
ESP8266 IR blaster With Opto - EasyEDA open source hardware lab <https://oshwlab.com/raptordemon/ESP8266_IR_blaster-f8f224faba554bf3bb6ce0e32759fc23_copy>
In EasyEDA open source hardware lab, open source square pools all kinds of electrical design engineerings together to realize resource sharing easily.
oshwlab.com


have a look at that and let me know if you need any other changes.

thanks
Dave
________________________________

**Comment by mdhiggins** [comment]
Looks good! Ordered a few for testing

**Comment by raptordemon** [comment]
Awesome let me know how it goes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdhiggins** [comment]
Built a few of the boards and its working great! Thanks for the update

**Comment by raptordemon** [comment]
thats great news! thanks for the feedback!!

________________________________
