### ISSUE TITLE
WifiManager still showing after connecting to network

### ISSUE THREAD

**Issue by shnax** [mdhiggins/ESP8266-HTTP-IR-Blaster#57]
I configure Wifi through the IRBlaster Configuration access point. Then the device connects to my network. I can access it through its IP, but it displays the Wifi Manger instead of the main dashboard.

The led on the board is still blinking as though it is not connected, but it is.

![image](https://user-images.githubusercontent.com/8661360/29487636-9e333dc2-84ca-11e7-908e-005829797b68.png)

**Comment by pansters** [comment]
Same problem here

**Comment by mdhiggins** [comment]
Make sure GPIO15 isn't connected to ground, that's the reset pin, it was recently changed from 13 to 15. If you're on wemos GPIO15 is always ground so I would change the reset pin to something different (or back to 13) in the blueprint

Conflicting with NodeMCU and WeMos

**Comment by shnax** [comment]
Thanks! Changing the config pin back to 13 fixed the issue.
![image](https://user-images.githubusercontent.com/8661360/29488788-047c1c56-84e0-11e7-9ef6-b455b72f04ba.png)
