### ISSUE TITLE
Wifi not being saved.

### ISSUE THREAD

**Issue by Junodixon** [mdhiggins/ESP8266-HTTP-IR-Blaster#58]
I am having a problem with the wifi being saved. Everything is working like it should be if I unplug or lose power for some reason it will reboot to the wifi config portal. Has anyone else had this problem?

**Comment by mdhiggins** [comment]
You have GPIO15 set to ground forcing configuration mode. You need to disconnect this pin from ground or change your reset pin in the blueprint
