### ISSUE TITLE
USECPERTICK no longer defined in libraries

### ISSUE THREAD

**Issue by gerryk** [mdhiggins/ESP8266-HTTP-IR-Blaster#59]
Getting the following build-time failure:

_IRController:809: error: 'USECPERTICK' was not declared in this scope_

Is it necessary to build against an earlier version of the IR libraries?

Using Arduino IDE: 1.8.4
IRemoteESP8266: https://github.com/markszabo/IRremoteESP8266/commit/2b75633e7c87875bfdb95117d19ceba3f9f804ab

**Comment by gerryk** [comment]
Rebuilt against IRremoteESP8299 2.1.1 
Builds fine.

This commit removes USECPERTICKS from the IRremote library.
https://github.com/markszabo/IRremoteESP8266/commit/8dd05c01561e29774402f69c9b7ccc1da4e3d381

**Comment by mdhiggins** [comment]
Fixed in latest update, should be compatible with latest version of IRRemote
