### ISSUE TITLE
No response from web server from WAN

### ISSUE THREAD

**Issue by Jo3yDaPh1sH** [mdhiggins/ESP8266-HTTP-IR-Blaster#6]
My problem is that I cannot access it from outside my network, the ifttt commands get sent by alexa but never make it back to the esp. If I use my External IP or my local ip from my home network it sees it and reports server is running, if I try from my mobile network I get a time out no response. I have the ports forwarded correctly, as the v1 had no issues. I also tried different ports and redoing the forwarding. I checked canyouseeme and the port that is forwarded takes about 5 seconds to respond closed, as any random port reports closed immediately so i think the request is at least making it there. Is there something I am missing or do you have any suggestions?

**Comment by mdhiggins** [comment]
That's very strange I can't say I've seen that problem before. If you wanna post a screenshot of your port forwarding settings I can take a look

**Comment by Jo3yDaPh1sH** [comment]
![screenshot 14](https://cloud.githubusercontent.com/assets/10469518/21964173/fd31c380-db14-11e6-994e-e44c89c1b75a.png)
Its very strange, I am going to factory reset my router and re do my settings just to see if there is an changes. Thanks

**Comment by mdhiggins** [comment]
Yeah I've got nothing. Your settings all look good not sure why. I suspect it has to do with the router more so than the code or the ESP8266.

**Comment by Jo3yDaPh1sH** [comment]
Yea, Its strange as the same router played just fine with the v1 code.  hmm maybe its got to do with my cell provider blocking ports, need to try it from a regular connection. On settings for ifttt I will post a screenshot just to make sure its nothing there.

**Comment by Jo3yDaPh1sH** [comment]
![screenshot 15](https://cloud.githubusercontent.com/assets/10469518/21965173/4dfd4358-db28-11e6-88c4-f808917c5c91.png)
Are these the correct settings for ifttt?

**Comment by mdhiggins** [comment]
That looks right. And I guess if you try that URL from an external source it doesn't work?

If you take that URL from IFTTT and replace with the local IP does it work? (Locally obviously)

Does just accessing the address without the command bring anything up?

http://pisco.asuscomm.com:6543/

Should bring up a message saying the server is running. 

Does your external IP work? As opposed to the ASUS DDNS

And I would also try disabling the hard coded IP address and let the ESP8266 connect with DHCP then forward to whatever address is assigned and see if that helps. You can do this by commenting out line 38. (WiFi.config...)

Let me know

**Comment by Jo3yDaPh1sH** [comment]
Yes it works locally,  I swapped out my router with a router running shibby tomato still no luck.  Locally it works with the lan ip, the wan ip and the ddns name. Reports correctly in serial monitor and does what it is supposed to. It does not work when I try it from my cell phone on the lte network or ifttt. The new ddns is as follows. 

http://joeydaphish.ddns.net:357/

Trying the DCHP to see if it helps

**Comment by mdhiggins** [comment]
If you try configuring the ESP8266 to use DHCP and then forward to that IP address does it make any difference?

**Comment by Jo3yDaPh1sH** [comment]
seems to have resolved it, hmmm very strange I would much prefer the static ip but I guess this will work!

**Comment by mdhiggins** [comment]
Once the dynamic IP is working I would just check what values were auto assigned and then hardcode those values. That's worked for me when I've run into trouble.

**Comment by Jo3yDaPh1sH** [comment]
Thanks, I just manually assigned the IP in my router DHCP config, so it shouldn't change, no harm no foul.
