### ISSUE TITLE
Weird errors when all elements wired

### ISSUE THREAD

**Issue by soltmar** [mdhiggins/ESP8266-HTTP-IR-Blaster#61]
At the beginning  I would like to flag that I'm newbe in Arduino world (have genral electronics experience)

After wiring up all stuff I'm receiving few different errors when accessing device information site. 
Device keeps restarting. Not sure how it is related but once it fails it fails all the time.

Scanning IR codes is ok.

Errors below are thrown followed by `wdt reset`. Everytime different and at random frequency...

`Exception 9: LoadStoreAlignmentCause: Load or store to an unaligned address
Decoding 20 results
0x40102f88: wDev_ProcessFiq at ?? line ?
0x4010311a: wDev_ProcessFiq at ?? line ?
0x40102f70: wDev_ProcessFiq at ?? line ?
0x4021c703: ppTxPkt at ?? line ?
0x401004d8: malloc at /Users/mariusz/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/umm_malloc/umm_malloc.c line 1664
0x402282f8: chm_start_op at ?? line ?
0x40244155: sys_timeout at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 296
0x40228294: chm_start_op at ?? line ?
0x4010511e: lmacTxFrame at ?? line ?
0x40101a8e: ppEnqueueRxq at ?? line ?
0x40230fa8: ets_timer_handler_isr at ?? line ?
0x4010185b: ppProcessTxQ at ?? line ?
0x40101896: ppProcessTxQ at ?? line ?
0x4021c3c2: ppPeocessRxPktHdr at ?? line ?
0x4021911f: loop_task at /Users/mariusz/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/core_esp8266_main.cpp line 56`

`Exception 0: Illegal instruction
Decoding 8 results
0x402452fc: etharp_arp_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 779
:  (inlined by) ethernet_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 1386
0x402452e4: etharp_arp_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 779
:  (inlined by) ethernet_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 1386
0x4010511e: lmacTxFrame at ?? line ?
0x4010185b: ppProcessTxQ at ?? line ?
0x40101896: ppProcessTxQ at ?? line ?
0x40230d97: ets_snprintf at ?? line ?`

`Exception 29: StoreProhibited: A store referenced a page mapped with an attribute that does not permit stores
Decoding 18 results
0x401035af: wDev_AppendRxBlocks at ?? line ?
0x4010311a: wDev_ProcessFiq at ?? line ?
0x4021c9e4: ppRecycleRxPkt at ?? line ?
0x402313d1: system_pp_recycle_rx_pkt at ?? line ?
0x402421be: pbuf_free at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/pbuf.c line 752
0x40227eab: ieee80211_parse_wmeparams at ?? line ?
0x402445b1: udp_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/udp.c line 114
0x40245e40: ip_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/ipv4/ip.c line 553
0x40103ff5: lmacIsIdle at ?? line ?
0x40245245: ethernet_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 1379
0x4010511e: lmacTxFrame at ?? line ?
0x40101a8e: ppEnqueueRxq at ?? line ?
0x4010185b: ppProcessTxQ at ?? line ?
0x40101896: ppProcessTxQ at ?? line ?
0x40230d97: ets_snprintf at ?? line ?`

`Exception 9: LoadStoreAlignmentCause: Load or store to an unaligned address
Decoding 12 results
0x40246161: ip4_addr_isbroadcast at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/ipv4/ip_addr.c line 70
0x40244c71: update_arp_entry at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 467
0x40223795: ieee80211_decap at ?? line ?
0x40103ff5: lmacIsIdle at ?? line ?
0x40245234: ethernet_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 1372
0x4010511e: lmacTxFrame at ?? line ?
0x40101a8e: ppEnqueueRxq at ?? line ?
0x4010185b: ppProcessTxQ at ?? line ?
0x40101896: ppProcessTxQ at ?? line ?
0x40230d97: ets_snprintf at ?? line ?`

`Exception 28: LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads
Decoding 11 results
0x40238c85: wps_registrar_add_pin at ?? line ?
0x40107960: pvPortMalloc at /Users/mariusz/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/heap.c line 13
0x40244c69: update_arp_entry at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 466 (discriminator 1)
0x40103ff5: lmacIsIdle at ?? line ?
0x402452e4: etharp_arp_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 779
:  (inlined by) ethernet_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c line 1386
0x4010511e: lmacTxFrame at ?? line ?
0x4010185b: ppProcessTxQ at ?? line ?
0x40101896: ppProcessTxQ at ?? line ?
0x40230d97: ets_snprintf at ?? line ?`

etc

**EDIT 1** 
I'm not really sure if this is something else now as even unwired this happens randomly.
Is it possible that I've done something to ESP itself or is it related with Arduino libraries ?

It is getting worst every time when I'm trying to see device site through local IP address 

**EDIT 2**
I've found that resetting nodemcu few times help for a while ...

**Comment by mdhiggins** [comment]
This almost seems like bad hardware, did you try on a different board?
