### ISSUE TITLE
Wifi does not get saved. GPIO15 Not set to ground

### ISSUE THREAD

**Issue by Rus-Punk** [mdhiggins/ESP8266-HTTP-IR-Blaster#64]
Every time i reboot it/loses power, i need to re configure the wifi setting.

**Comment by mdhiggins** [comment]
Are you sure? That’s the only reason that would happen. What hardware you are using? NodeMCU? Did you try changing the reset configuration pin to something else and see if I makes a difference?

**Comment by mdhiggins** [comment]
Did some digging and it looks like on certain NodeMCU builds GPIO15 defaults to the LOW state without being set to ground and this can cause and endless settings loop
Going to try changing the reset pin to GPIO10 (the quest for a good reset pin continues)
Just pushed an update today that changes the pin

**Comment by mdhiggins** [comment]
Yeah looks like GPIO15 was no good, latest update uses 10

**Comment by Rus-Punk** [comment]
Cool, thanks for your work.
