### ISSUE TITLE
Humax HD3/4 German Sky Cable receiver

### ISSUE THREAD

**Issue by wagnetor** [mdhiggins/ESP8266-HTTP-IR-Blaster#70]
Hello,
now i have an other problem.
If i receive ir-codes from the original remote control (Humax HD3/4 German Sky Cable receiver)l, i get everytime another raw-code.
It should be an RC6 code with toggle bit. The IRBlaster send the code, but the receiver nothing do.
Have everybody an idea or the raw-codes to work for this receiver?

Thanks

**Comment by mdhiggins** [comment]
I would raise this question over here
https://github.com/markszabo/IRremoteESP8266

Its an issue with the IRremote library beyond what I am capable of supporting
