### ISSUE TITLE
Not able to discover devices in Alexa app

### ISSUE THREAD

**Issue by bhattvishal** [mdhiggins/ESP8266-HTTP-IR-Blaster#73]
I add added devices at https://tehpsyc.pythonanywhere.com, but they are not discovered in the Alexa app.

**Comment by mdhiggins** [comment]
And the skill is installed and authenticated? And you’re using a US Amazon account on both the website and the skill?

**Comment by bhattvishal** [comment]
Hi, Thanks for the quick reply.

Yes, the skill is installed and authenticated. I am not using US Amazon account, its an India Amazon account. But, I used the beta tester link to enable the skill from web. Does this only work with US Amazon account?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mdhiggins** [comment]
That's the issue. Amazon blocks device discovery for accounts outside of the US for any skill using smart home V3

**Comment by mdhiggins** [comment]
Skill was just submitted for review to the UK and India skill repo
