### ISSUE TITLE
Address

### ISSUE THREAD

**Issue by groovington** [mdhiggins/ESP8266-HTTP-IR-Blaster#75]
How do I send the "Address" portion of the IR code? Whenever I capture a code it has an address, when i send the address is just 0. The codes don't seem to work so I am guessing the address portion is relevant?

**Comment by mdhiggins** [comment]
Address portion is usually irrelevant actually. What kind of code are you sending?

**Comment by groovington** [comment]
Panasonic TV remote commands, They only work if i send them as raw

**Comment by mdhiggins** [comment]
Ah Panasonic is the one exception where address does matter. You can add the address by adding &address= to your URL

**Comment by groovington** [comment]
Sending http://10.10.10.249:80/msg?code=40040100BCBD:PANASONIC:48&address=0x4004&pulse=10&pass=****

Still shows the address as 0, and still doesnt work.

**Comment by dham1012** [comment]
I've found that you need to convert the address from hex to dec. Try using 16388 as the address.
You might not need the 40040 in the code section either. I send as json so not sure if that makes any difference. An example of json is as follows

`{"type":PANASONIC,"data":D000805,"length":48,"address":16388}`

**Comment by groovington** [comment]
{"type":PANASONIC,"data":0100BCBD,"length":48,"address":16388,"pulse":10}

its getting there but something isn't quite right. The TV is responding now, but not actually getting the right command by the looks of it.

**Comment by dham1012** [comment]
try 
`{"type":PANASONIC,"data":100BCBD,"length":48,"address":16388,"pulse":10}`

**Comment by dham1012** [comment]
Looks very similar to my Panasonic codes, to turn on I use
`{"type":PANASONIC,"data":100BCBD,"length":48,"address":16388,"pdelay":30,"pulse":5}`
off is 
`{"type":PANASONIC,"data":100BCBD,"length":48,"address":16388}`

**Comment by mdhiggins** [comment]
You also do not need to use json to send the address, this should work
`http://10.10.10.249/msg?code=40040100BCBD:PANASONIC:48&address=16388&pulse=10&pass=xxxx`

Also I'll push down an update that will allow HEX or DEC

**Comment by mdhiggins** [comment]
Update pushed

**Comment by mdhiggins** [comment]
<img width="950" alt="screen shot 2017-11-18 at 3 45 12 pm" src="https://user-images.githubusercontent.com/3608298/32984587-8ff06dd0-cc77-11e7-9050-e0e2021bf6c2.png">

Looks like the address is displaying as it should, don't have a Panasonic TV to test on however
That was using address=1638 or address=0x4004

**Comment by mdhiggins** [comment]
Any progress?

**Comment by dham1012** [comment]
I've not chance to update my live unit to test sending a code and it displaying hex or dec. Will try and test later this evening and let you know.

**Comment by dham1012** [comment]
Can confirm that using HEX or DEC for address works as expected and transmits and is understood by (in my case Panasonic) TV. DEC is always displayed in web interface regardless if HEX is used.

**Comment by mdhiggins** [comment]
I pushed an update this morning that makes it always display HEX so it’s consistent across the board but glad to hear it’s working
