### ISSUE TITLE
Low performance because of stupid delay conditions

### ISSUE THREAD

**Issue by rselec** [mdhiggins/ESP8266-HTTP-IR-Blaster#77]
Hi I might found a bug in your great SW:

In line 1265 and 1266 you compare against p- and rdelay to decide wehter a delay is needed, but that doesn't make sense. I think you want to compare against pulse and repeat to avoid unnecessary delays if repeat and pulse is for e.g. 1.

I've changed the conditions and that boosts performance!

Best, Bimbo385

**Comment by mdhiggins** [comment]
Ah you're right, that was an oversight, good catch
Updated to correct this, thank you

**Comment by rselec** [comment]
That was pretty fast, same (copy&paste) in the rawblast function.

Nice weekend!

**Comment by mdhiggins** [comment]
Fixed that one too, thanks
