### ISSUE TITLE
Always blank after powered down

### ISSUE THREAD

**Issue by stephenmhall** [mdhiggins/ESP8266-HTTP-IR-Blaster#82]
Whenever I restart the wemos D1 mini there are no IR controls stored. Should they be save in the file system between restarts?

**Comment by mdhiggins** [comment]
No they are not saved. Storing them doesn’t really provide any benefit anyway it’s more just for debugging and setup

**Comment by stephenmhall** [comment]
OK. I think I didn't get the point :) after it has been received you just need to keep a copy of the message to send. I was thinking it had to keep a copy of the message to send out but it's all contained in the http message. Thanks I understand now.
