### ISSUE TITLE
In Channel Controller What should be the format of Button

### ISSUE THREAD

**Issue by shariramani** [mdhiggins/ESP8266-HTTP-IR-Blaster#93]
I tried with following but Alexa gave error
'80BF19E6':'NEC':32:0
Can you give me a example?

**Comment by mdhiggins** [comment]
The example is on the webpage in the placeholder text.

For that code
data:’80BF19E6’,type:’NEC’,length:32

**Comment by shariramani** [comment]
I used the channel button format as suggested by you, but still Alexa says
that command is not supported by your TV.
Next channel and down channel commands work fine.
