### ISSUE TITLE
fatal error: sha256.h: No such file or directory 

### ISSUE THREAD

**Issue by anilet** [mdhiggins/ESP8266-HTTP-IR-Blaster#94]
I am trying to upload this to a NodeMCU from Ubuntu
and getting 
/projects/ir/IRController/IRController.ino:15:20: fatal error: sha256.h: No such file or directory
 #include "sha256.h"
I could not find sha256 library in Arduino IDE,
Where can I find it?

**Comment by mdhiggins** [comment]
https://github.com/jjssoftware/Cryptosuite

Install Cryptosuite

**Comment by anilet** [comment]
Thanks, I re-read the instructions and figured it out just after posting
